// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: app_kv.sql

package db

import (
	"context"
	"time"
)

const deleteExpiredKV = `-- name: DeleteExpiredKV :exec
DELETE FROM app_kv WHERE expires_at < NOW() - interval '1 hour'
`

func (q *Queries) DeleteExpiredKV(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredKV)
	return err
}

const getKV = `-- name: GetKV :one
SELECT value FROM app_kv WHERE key = $1 AND expires_at > NOW()
`

func (q *Queries) GetKV(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRowContext(ctx, getKV, key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const rateLimitHit = `-- name: RateLimitHit :one
INSERT INTO app_kv (key, count, expires_at)
VALUES ($1, 1, NOW() + make_interval(secs => $2))
ON CONFLICT (key) DO UPDATE SET
    count = CASE WHEN app_kv.expires_at <= NOW() THEN 1 ELSE app_kv.count + 1 END,
    expires_at = CASE WHEN app_kv.expires_at <= NOW() THEN NOW() + make_interval(secs => $2) ELSE app_kv.expires_at END
RETURNING count, expires_at
`

type RateLimitHitParams struct {
	Key  string  `json:"key"`
	Secs float64 `json:"secs"`
}

type RateLimitHitRow struct {
	Count     int32     `json:"count"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) RateLimitHit(ctx context.Context, arg RateLimitHitParams) (RateLimitHitRow, error) {
	row := q.db.QueryRowContext(ctx, rateLimitHit, arg.Key, arg.Secs)
	var i RateLimitHitRow
	err := row.Scan(&i.Count, &i.ExpiresAt)
	return i, err
}

const setKV = `-- name: SetKV :exec
INSERT INTO app_kv (key, value, expires_at)
VALUES ($1, $2, NOW() + make_interval(secs => $3))
ON CONFLICT (key) DO UPDATE SET value = $2, expires_at = NOW() + make_interval(secs => $3)
`

type SetKVParams struct {
	Key   string  `json:"key"`
	Value string  `json:"value"`
	Secs  float64 `json:"secs"`
}

func (q *Queries) SetKV(ctx context.Context, arg SetKVParams) error {
	_, err := q.db.ExecContext(ctx, setKV, arg.Key, arg.Value, arg.Secs)
	return err
}
