// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audio_transcodes.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const completeAudioTranscode = `-- name: CompleteAudioTranscode :exec
UPDATE audio_transcodes SET status = 'COMPLETED', transcoded_file_url = $2, updated_at = NOW() WHERE id = $1
`

type CompleteAudioTranscodeParams struct {
	ID                uuid.UUID      `json:"id"`
	TranscodedFileUrl sql.NullString `json:"transcoded_file_url"`
}

func (q *Queries) CompleteAudioTranscode(ctx context.Context, arg CompleteAudioTranscodeParams) error {
	_, err := q.db.ExecContext(ctx, completeAudioTranscode, arg.ID, arg.TranscodedFileUrl)
	return err
}

const failAudioTranscode = `-- name: FailAudioTranscode :exec
UPDATE audio_transcodes SET status = 'FAILED', error_message = $2, updated_at = NOW() WHERE id = $1
`

type FailAudioTranscodeParams struct {
	ID           uuid.UUID      `json:"id"`
	ErrorMessage sql.NullString `json:"error_message"`
}

func (q *Queries) FailAudioTranscode(ctx context.Context, arg FailAudioTranscodeParams) error {
	_, err := q.db.ExecContext(ctx, failAudioTranscode, arg.ID, arg.ErrorMessage)
	return err
}

const getPendingAudioTranscodes = `-- name: GetPendingAudioTranscodes :many
SELECT t.id, t.attachment_id, a.file_url, a.file_type
FROM audio_transcodes t
JOIN attachments a ON t.attachment_id = a.id
WHERE t.status = 'PENDING'
LIMIT 10
FOR UPDATE OF t SKIP LOCKED
`

type GetPendingAudioTranscodesRow struct {
	ID           uuid.UUID `json:"id"`
	AttachmentID uuid.UUID `json:"attachment_id"`
	FileUrl      string    `json:"file_url"`
	FileType     string    `json:"file_type"`
}

func (q *Queries) GetPendingAudioTranscodes(ctx context.Context) ([]GetPendingAudioTranscodesRow, error) {
	rows, err := q.db.QueryContext(ctx, getPendingAudioTranscodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPendingAudioTranscodesRow
	for rows.Next() {
		var i GetPendingAudioTranscodesRow
		if err := rows.Scan(
			&i.ID,
			&i.AttachmentID,
			&i.FileUrl,
			&i.FileType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertAudioTranscode = `-- name: InsertAudioTranscode :exec
INSERT INTO audio_transcodes (attachment_id) VALUES ($1) ON CONFLICT (attachment_id) DO NOTHING
`

func (q *Queries) InsertAudioTranscode(ctx context.Context, attachmentID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, insertAudioTranscode, attachmentID)
	return err
}

const setAudioTranscodeProcessing = `-- name: SetAudioTranscodeProcessing :exec
UPDATE audio_transcodes SET status = 'PROCESSING', updated_at = NOW() WHERE id = $1
`

func (q *Queries) SetAudioTranscodeProcessing(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, setAudioTranscodeProcessing, id)
	return err
}
