// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: device_tokens.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const deleteDeviceToken = `-- name: DeleteDeviceToken :exec
DELETE FROM device_tokens WHERE fcm_token = $1
`

func (q *Queries) DeleteDeviceToken(ctx context.Context, fcmToken string) error {
	_, err := q.db.ExecContext(ctx, deleteDeviceToken, fcmToken)
	return err
}

const getDeviceTokensForUser = `-- name: GetDeviceTokensForUser :many
SELECT fcm_token FROM device_tokens WHERE user_id = $1 AND org_id = $2
`

type GetDeviceTokensForUserParams struct {
	UserID uuid.UUID `json:"user_id"`
	OrgID  uuid.UUID `json:"org_id"`
}

func (q *Queries) GetDeviceTokensForUser(ctx context.Context, arg GetDeviceTokensForUserParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getDeviceTokensForUser, arg.UserID, arg.OrgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var fcm_token string
		if err := rows.Scan(&fcm_token); err != nil {
			return nil, err
		}
		items = append(items, fcm_token)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDeviceToken = `-- name: UpsertDeviceToken :exec
INSERT INTO device_tokens (user_id, org_id, platform, fcm_token)
VALUES ($1, $2, $3, $4)
ON CONFLICT (fcm_token) DO UPDATE SET
    user_id = $1,
    org_id = $2,
    platform = $3,
    last_seen_at = NOW()
`

type UpsertDeviceTokenParams struct {
	UserID   uuid.UUID `json:"user_id"`
	OrgID    uuid.UUID `json:"org_id"`
	Platform string    `json:"platform"`
	FcmToken string    `json:"fcm_token"`
}

func (q *Queries) UpsertDeviceToken(ctx context.Context, arg UpsertDeviceTokenParams) error {
	_, err := q.db.ExecContext(ctx, upsertDeviceToken,
		arg.UserID,
		arg.OrgID,
		arg.Platform,
		arg.FcmToken,
	)
	return err
}
