// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type ParticipantRole string

const (
	ParticipantRoleASSIGNEE   ParticipantRole = "ASSIGNEE"
	ParticipantRoleSUBSCRIBER ParticipantRole = "SUBSCRIBER"
)

func (e *ParticipantRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ParticipantRole(s)
	case string:
		*e = ParticipantRole(s)
	default:
		return fmt.Errorf("unsupported scan type for ParticipantRole: %T", src)
	}
	return nil
}

type NullParticipantRole struct {
	ParticipantRole ParticipantRole `json:"participant_role"`
	Valid           bool            `json:"valid"` // Valid is true if ParticipantRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullParticipantRole) Scan(value interface{}) error {
	if value == nil {
		ns.ParticipantRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ParticipantRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullParticipantRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ParticipantRole), nil
}

type ReminderChannel string

const (
	ReminderChannelWHATSAPP ReminderChannel = "WHATSAPP"
	ReminderChannelEMAIL    ReminderChannel = "EMAIL"
)

func (e *ReminderChannel) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ReminderChannel(s)
	case string:
		*e = ReminderChannel(s)
	default:
		return fmt.Errorf("unsupported scan type for ReminderChannel: %T", src)
	}
	return nil
}

type NullReminderChannel struct {
	ReminderChannel ReminderChannel `json:"reminder_channel"`
	Valid           bool            `json:"valid"` // Valid is true if ReminderChannel is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullReminderChannel) Scan(value interface{}) error {
	if value == nil {
		ns.ReminderChannel, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ReminderChannel.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullReminderChannel) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ReminderChannel), nil
}

type ReminderStatus string

const (
	ReminderStatusPENDING   ReminderStatus = "PENDING"
	ReminderStatusSENT      ReminderStatus = "SENT"
	ReminderStatusCANCELLED ReminderStatus = "CANCELLED"
)

func (e *ReminderStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ReminderStatus(s)
	case string:
		*e = ReminderStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ReminderStatus: %T", src)
	}
	return nil
}

type NullReminderStatus struct {
	ReminderStatus ReminderStatus `json:"reminder_status"`
	Valid          bool           `json:"valid"` // Valid is true if ReminderStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullReminderStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ReminderStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ReminderStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullReminderStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ReminderStatus), nil
}

type TaskFulfillmentStatus string

const (
	TaskFulfillmentStatusPENDING   TaskFulfillmentStatus = "PENDING"
	TaskFulfillmentStatusCOMPLETED TaskFulfillmentStatus = "COMPLETED"
)

func (e *TaskFulfillmentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TaskFulfillmentStatus(s)
	case string:
		*e = TaskFulfillmentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TaskFulfillmentStatus: %T", src)
	}
	return nil
}

type NullTaskFulfillmentStatus struct {
	TaskFulfillmentStatus TaskFulfillmentStatus `json:"task_fulfillment_status"`
	Valid                 bool                  `json:"valid"` // Valid is true if TaskFulfillmentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTaskFulfillmentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TaskFulfillmentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TaskFulfillmentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTaskFulfillmentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TaskFulfillmentStatus), nil
}

type TaskStatus string

const (
	TaskStatusOPEN   TaskStatus = "OPEN"
	TaskStatusCLOSED TaskStatus = "CLOSED"
)

func (e *TaskStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TaskStatus(s)
	case string:
		*e = TaskStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TaskStatus: %T", src)
	}
	return nil
}

type NullTaskStatus struct {
	TaskStatus TaskStatus `json:"task_status"`
	Valid      bool       `json:"valid"` // Valid is true if TaskStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTaskStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TaskStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TaskStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTaskStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TaskStatus), nil
}

type UserRole string

const (
	UserRoleSUPERADMIN UserRole = "SUPERADMIN"
	UserRoleADMIN      UserRole = "ADMIN"
	UserRoleEMPLOYEE   UserRole = "EMPLOYEE"
	UserRoleDEFAULT    UserRole = "DEFAULT"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"user_role"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type UserStatus string

const (
	UserStatusINVITED   UserStatus = "INVITED"
	UserStatusACTIVE    UserStatus = "ACTIVE"
	UserStatusSUSPENDED UserStatus = "SUSPENDED"
)

func (e *UserStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserStatus(s)
	case string:
		*e = UserStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for UserStatus: %T", src)
	}
	return nil
}

type NullUserStatus struct {
	UserStatus UserStatus `json:"user_status"`
	Valid      bool       `json:"valid"` // Valid is true if UserStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserStatus) Scan(value interface{}) error {
	if value == nil {
		ns.UserStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserStatus), nil
}

type Organization struct {
	ID        uuid.UUID      `json:"id"`
	Name      string         `json:"name"`
	Domain    sql.NullString `json:"domain"`
	CreatedAt sql.NullTime   `json:"created_at"`
}

type Reminder struct {
	ID          uuid.UUID          `json:"id"`
	TaskID      uuid.UUID          `json:"task_id"`
	ScheduledAt time.Time          `json:"scheduled_at"`
	Channel     ReminderChannel    `json:"channel"`
	Status      NullReminderStatus `json:"status"`
	CreatedAt   sql.NullTime       `json:"created_at"`
}

type Task struct {
	ID                uuid.UUID                 `json:"id"`
	TeamID            uuid.UUID                 `json:"team_id"`
	Title             string                    `json:"title"`
	Description       sql.NullString            `json:"description"`
	Status            NullTaskStatus            `json:"status"`
	FulfillmentStatus NullTaskFulfillmentStatus `json:"fulfillment_status"`
	CreatedBy         uuid.UUID                 `json:"created_by"`
	DueDate           sql.NullTime              `json:"due_date"`
	CreatedAt         sql.NullTime              `json:"created_at"`
}

type TaskParticipant struct {
	TaskID uuid.UUID       `json:"task_id"`
	UserID uuid.UUID       `json:"user_id"`
	Role   ParticipantRole `json:"role"`
}

type TaskUpdate struct {
	ID        uuid.UUID     `json:"id"`
	TaskID    uuid.UUID     `json:"task_id"`
	UserID    uuid.NullUUID `json:"user_id"`
	Content   string        `json:"content"`
	CreatedAt sql.NullTime  `json:"created_at"`
}

type Team struct {
	ID        uuid.UUID    `json:"id"`
	OrgID     uuid.UUID    `json:"org_id"`
	Name      string       `json:"name"`
	AdminID   uuid.UUID    `json:"admin_id"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type TeamMember struct {
	TeamID uuid.UUID `json:"team_id"`
	UserID uuid.UUID `json:"user_id"`
}

type User struct {
	ID          uuid.UUID      `json:"id"`
	OrgID       uuid.UUID      `json:"org_id"`
	Status      NullUserStatus `json:"status"`
	FirstName   sql.NullString `json:"first_name"`
	LastName    sql.NullString `json:"last_name"`
	EmailID     string         `json:"email_id"`
	PhoneNumber sql.NullString `json:"phone_number"`
	Role        UserRole       `json:"role"`
	CreatedAt   sql.NullTime   `json:"created_at"`
}

type UserCredential struct {
	UserID       uuid.UUID    `json:"user_id"`
	PasswordHash string       `json:"password_hash"`
	UpdatedAt    sql.NullTime `json:"updated_at"`
}
