// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type AudioTranscodeStatus string

const (
	AudioTranscodeStatusPENDING    AudioTranscodeStatus = "PENDING"
	AudioTranscodeStatusPROCESSING AudioTranscodeStatus = "PROCESSING"
	AudioTranscodeStatusCOMPLETED  AudioTranscodeStatus = "COMPLETED"
	AudioTranscodeStatusFAILED     AudioTranscodeStatus = "FAILED"
)

func (e *AudioTranscodeStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AudioTranscodeStatus(s)
	case string:
		*e = AudioTranscodeStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for AudioTranscodeStatus: %T", src)
	}
	return nil
}

type NullAudioTranscodeStatus struct {
	AudioTranscodeStatus AudioTranscodeStatus `json:"audio_transcode_status"`
	Valid                bool                 `json:"valid"` // Valid is true if AudioTranscodeStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAudioTranscodeStatus) Scan(value interface{}) error {
	if value == nil {
		ns.AudioTranscodeStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AudioTranscodeStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAudioTranscodeStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AudioTranscodeStatus), nil
}

type ParticipantRole string

const (
	ParticipantRoleASSIGNEE   ParticipantRole = "ASSIGNEE"
	ParticipantRoleSUBSCRIBER ParticipantRole = "SUBSCRIBER"
)

func (e *ParticipantRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ParticipantRole(s)
	case string:
		*e = ParticipantRole(s)
	default:
		return fmt.Errorf("unsupported scan type for ParticipantRole: %T", src)
	}
	return nil
}

type NullParticipantRole struct {
	ParticipantRole ParticipantRole `json:"participant_role"`
	Valid           bool            `json:"valid"` // Valid is true if ParticipantRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullParticipantRole) Scan(value interface{}) error {
	if value == nil {
		ns.ParticipantRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ParticipantRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullParticipantRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ParticipantRole), nil
}

type RecurrenceUnit string

const (
	RecurrenceUnitMINUTES RecurrenceUnit = "MINUTES"
	RecurrenceUnitHOURS   RecurrenceUnit = "HOURS"
	RecurrenceUnitDAYS    RecurrenceUnit = "DAYS"
	RecurrenceUnitWEEKS   RecurrenceUnit = "WEEKS"
	RecurrenceUnitMONTHS  RecurrenceUnit = "MONTHS"
)

func (e *RecurrenceUnit) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RecurrenceUnit(s)
	case string:
		*e = RecurrenceUnit(s)
	default:
		return fmt.Errorf("unsupported scan type for RecurrenceUnit: %T", src)
	}
	return nil
}

type NullRecurrenceUnit struct {
	RecurrenceUnit RecurrenceUnit `json:"recurrence_unit"`
	Valid          bool           `json:"valid"` // Valid is true if RecurrenceUnit is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRecurrenceUnit) Scan(value interface{}) error {
	if value == nil {
		ns.RecurrenceUnit, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RecurrenceUnit.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRecurrenceUnit) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RecurrenceUnit), nil
}

type ReminderChannel string

const (
	ReminderChannelWHATSAPP ReminderChannel = "WHATSAPP"
	ReminderChannelEMAIL    ReminderChannel = "EMAIL"
)

func (e *ReminderChannel) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ReminderChannel(s)
	case string:
		*e = ReminderChannel(s)
	default:
		return fmt.Errorf("unsupported scan type for ReminderChannel: %T", src)
	}
	return nil
}

type NullReminderChannel struct {
	ReminderChannel ReminderChannel `json:"reminder_channel"`
	Valid           bool            `json:"valid"` // Valid is true if ReminderChannel is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullReminderChannel) Scan(value interface{}) error {
	if value == nil {
		ns.ReminderChannel, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ReminderChannel.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullReminderChannel) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ReminderChannel), nil
}

type ReminderStatus string

const (
	ReminderStatusPENDING   ReminderStatus = "PENDING"
	ReminderStatusSENT      ReminderStatus = "SENT"
	ReminderStatusCANCELLED ReminderStatus = "CANCELLED"
)

func (e *ReminderStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ReminderStatus(s)
	case string:
		*e = ReminderStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ReminderStatus: %T", src)
	}
	return nil
}

type NullReminderStatus struct {
	ReminderStatus ReminderStatus `json:"reminder_status"`
	Valid          bool           `json:"valid"` // Valid is true if ReminderStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullReminderStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ReminderStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ReminderStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullReminderStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ReminderStatus), nil
}

type ScoreEventType string

const (
	ScoreEventTypeONTIMECOMPLETION ScoreEventType = "ON_TIME_COMPLETION"
	ScoreEventTypeLATECOMPLETION   ScoreEventType = "LATE_COMPLETION"
	ScoreEventTypeMISSEDDEADLINE   ScoreEventType = "MISSED_DEADLINE"
	ScoreEventTypeREJECTION        ScoreEventType = "REJECTION"
)

func (e *ScoreEventType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ScoreEventType(s)
	case string:
		*e = ScoreEventType(s)
	default:
		return fmt.Errorf("unsupported scan type for ScoreEventType: %T", src)
	}
	return nil
}

type NullScoreEventType struct {
	ScoreEventType ScoreEventType `json:"score_event_type"`
	Valid          bool           `json:"valid"` // Valid is true if ScoreEventType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullScoreEventType) Scan(value interface{}) error {
	if value == nil {
		ns.ScoreEventType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ScoreEventType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullScoreEventType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ScoreEventType), nil
}

type SystemRole string

const (
	SystemRoleSUPERADMIN SystemRole = "SUPER_ADMIN"
	SystemRoleADMIN      SystemRole = "ADMIN"
	SystemRoleEMPLOYEE   SystemRole = "EMPLOYEE"
)

func (e *SystemRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SystemRole(s)
	case string:
		*e = SystemRole(s)
	default:
		return fmt.Errorf("unsupported scan type for SystemRole: %T", src)
	}
	return nil
}

type NullSystemRole struct {
	SystemRole SystemRole `json:"system_role"`
	Valid      bool       `json:"valid"` // Valid is true if SystemRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSystemRole) Scan(value interface{}) error {
	if value == nil {
		ns.SystemRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SystemRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSystemRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SystemRole), nil
}

type TaskFulfillmentStatus string

const (
	TaskFulfillmentStatusPENDING   TaskFulfillmentStatus = "PENDING"
	TaskFulfillmentStatusCOMPLETED TaskFulfillmentStatus = "COMPLETED"
)

func (e *TaskFulfillmentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TaskFulfillmentStatus(s)
	case string:
		*e = TaskFulfillmentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TaskFulfillmentStatus: %T", src)
	}
	return nil
}

type NullTaskFulfillmentStatus struct {
	TaskFulfillmentStatus TaskFulfillmentStatus `json:"task_fulfillment_status"`
	Valid                 bool                  `json:"valid"` // Valid is true if TaskFulfillmentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTaskFulfillmentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TaskFulfillmentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TaskFulfillmentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTaskFulfillmentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TaskFulfillmentStatus), nil
}

type TaskReviewStatus string

const (
	TaskReviewStatusUNSUBMITTED TaskReviewStatus = "UNSUBMITTED"
	TaskReviewStatusPENDING     TaskReviewStatus = "PENDING"
	TaskReviewStatusAPPROVED    TaskReviewStatus = "APPROVED"
	TaskReviewStatusREJECTED    TaskReviewStatus = "REJECTED"
)

func (e *TaskReviewStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TaskReviewStatus(s)
	case string:
		*e = TaskReviewStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TaskReviewStatus: %T", src)
	}
	return nil
}

type NullTaskReviewStatus struct {
	TaskReviewStatus TaskReviewStatus `json:"task_review_status"`
	Valid            bool             `json:"valid"` // Valid is true if TaskReviewStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTaskReviewStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TaskReviewStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TaskReviewStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTaskReviewStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TaskReviewStatus), nil
}

type TaskStatus string

const (
	TaskStatusOPEN   TaskStatus = "OPEN"
	TaskStatusCLOSED TaskStatus = "CLOSED"
)

func (e *TaskStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TaskStatus(s)
	case string:
		*e = TaskStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TaskStatus: %T", src)
	}
	return nil
}

type NullTaskStatus struct {
	TaskStatus TaskStatus `json:"task_status"`
	Valid      bool       `json:"valid"` // Valid is true if TaskStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTaskStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TaskStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TaskStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTaskStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TaskStatus), nil
}

type TeamRoleEnum string

const (
	TeamRoleEnumTEAMADMIN TeamRoleEnum = "TEAM_ADMIN"
	TeamRoleEnumMEMBER    TeamRoleEnum = "MEMBER"
)

func (e *TeamRoleEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TeamRoleEnum(s)
	case string:
		*e = TeamRoleEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for TeamRoleEnum: %T", src)
	}
	return nil
}

type NullTeamRoleEnum struct {
	TeamRoleEnum TeamRoleEnum `json:"team_role_enum"`
	Valid        bool         `json:"valid"` // Valid is true if TeamRoleEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTeamRoleEnum) Scan(value interface{}) error {
	if value == nil {
		ns.TeamRoleEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TeamRoleEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTeamRoleEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TeamRoleEnum), nil
}

type TranscriptionStatus string

const (
	TranscriptionStatusPENDING    TranscriptionStatus = "PENDING"
	TranscriptionStatusPROCESSING TranscriptionStatus = "PROCESSING"
	TranscriptionStatusCOMPLETED  TranscriptionStatus = "COMPLETED"
	TranscriptionStatusFAILED     TranscriptionStatus = "FAILED"
)

func (e *TranscriptionStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TranscriptionStatus(s)
	case string:
		*e = TranscriptionStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TranscriptionStatus: %T", src)
	}
	return nil
}

type NullTranscriptionStatus struct {
	TranscriptionStatus TranscriptionStatus `json:"transcription_status"`
	Valid               bool                `json:"valid"` // Valid is true if TranscriptionStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTranscriptionStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TranscriptionStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TranscriptionStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTranscriptionStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TranscriptionStatus), nil
}

type UserStatus string

const (
	UserStatusINVITED   UserStatus = "INVITED"
	UserStatusACTIVE    UserStatus = "ACTIVE"
	UserStatusSUSPENDED UserStatus = "SUSPENDED"
)

func (e *UserStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserStatus(s)
	case string:
		*e = UserStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for UserStatus: %T", src)
	}
	return nil
}

type NullUserStatus struct {
	UserStatus UserStatus `json:"user_status"`
	Valid      bool       `json:"valid"` // Valid is true if UserStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserStatus) Scan(value interface{}) error {
	if value == nil {
		ns.UserStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserStatus), nil
}

type Attachment struct {
	ID            uuid.UUID     `json:"id"`
	TaskID        uuid.NullUUID `json:"task_id"`
	TaskUpdateID  uuid.NullUUID `json:"task_update_id"`
	TaskCommentID uuid.NullUUID `json:"task_comment_id"`
	FileName      string        `json:"file_name"`
	FileUrl       string        `json:"file_url"`
	FileType      string        `json:"file_type"`
	FileSizeBytes sql.NullInt64 `json:"file_size_bytes"`
	UploadedBy    uuid.UUID     `json:"uploaded_by"`
	CreatedAt     sql.NullTime  `json:"created_at"`
}

type AttendanceRecord struct {
	ID             uuid.UUID      `json:"id"`
	UserID         uuid.UUID      `json:"user_id"`
	OrgID          uuid.UUID      `json:"org_id"`
	TargetFileUri  sql.NullString `json:"target_file_uri"`
	Present        sql.NullBool   `json:"present"`
	Status         string         `json:"status"`
	AttendanceDate sql.NullTime   `json:"attendance_date"`
	CreatedAt      sql.NullTime   `json:"created_at"`
	UpdatedAt      sql.NullTime   `json:"updated_at"`
}

type AudioTranscode struct {
	ID                uuid.UUID                `json:"id"`
	AttachmentID      uuid.UUID                `json:"attachment_id"`
	Status            NullAudioTranscodeStatus `json:"status"`
	TranscodedFileUrl sql.NullString           `json:"transcoded_file_url"`
	ErrorMessage      sql.NullString           `json:"error_message"`
	CreatedAt         sql.NullTime             `json:"created_at"`
	UpdatedAt         sql.NullTime             `json:"updated_at"`
}

type DeviceToken struct {
	ID         uuid.UUID    `json:"id"`
	UserID     uuid.UUID    `json:"user_id"`
	OrgID      uuid.UUID    `json:"org_id"`
	Platform   string       `json:"platform"`
	FcmToken   string       `json:"fcm_token"`
	CreatedAt  sql.NullTime `json:"created_at"`
	LastSeenAt sql.NullTime `json:"last_seen_at"`
}

type EmployeeScore struct {
	ID              uuid.UUID      `json:"id"`
	TaskID          uuid.UUID      `json:"task_id"`
	UserID          uuid.UUID      `json:"user_id"`
	TeamID          uuid.UUID      `json:"team_id"`
	OrgID           uuid.UUID      `json:"org_id"`
	EventType       ScoreEventType `json:"event_type"`
	PointsAwarded   int32          `json:"points_awarded"`
	DueDateSnapshot sql.NullTime   `json:"due_date_snapshot"`
	EventAt         time.Time      `json:"event_at"`
	Superseded      bool           `json:"superseded"`
	CreatedAt       sql.NullTime   `json:"created_at"`
}

type FaceValidationJob struct {
	ID        uuid.UUID      `json:"id"`
	UserID    uuid.UUID      `json:"user_id"`
	ObjectKey string         `json:"object_key"`
	Status    string         `json:"status"`
	Reason    sql.NullString `json:"reason"`
	CreatedAt sql.NullTime   `json:"created_at"`
}

type Notification struct {
	ID        uuid.UUID    `json:"id"`
	UserID    uuid.UUID    `json:"user_id"`
	OrgID     uuid.UUID    `json:"org_id"`
	Title     string       `json:"title"`
	Message   string       `json:"message"`
	IsRead    sql.NullBool `json:"is_read"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type OrgMembership struct {
	ID        uuid.UUID    `json:"id"`
	UserID    uuid.UUID    `json:"user_id"`
	OrgID     uuid.UUID    `json:"org_id"`
	Status    UserStatus   `json:"status"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type Organization struct {
	ID                uuid.UUID      `json:"id"`
	Name              string         `json:"name"`
	Domain            sql.NullString `json:"domain"`
	AttendanceEnabled bool           `json:"attendance_enabled"`
	CreatedAt         sql.NullTime   `json:"created_at"`
}

type Reminder struct {
	ID              uuid.UUID          `json:"id"`
	TaskID          uuid.UUID          `json:"task_id"`
	ScheduledAt     time.Time          `json:"scheduled_at"`
	Channel         ReminderChannel    `json:"channel"`
	Status          NullReminderStatus `json:"status"`
	RecurrenceValue sql.NullInt32      `json:"recurrence_value"`
	RecurrenceUnit  NullRecurrenceUnit `json:"recurrence_unit"`
	CreatedAt       sql.NullTime       `json:"created_at"`
	IsSystemSpawned bool               `json:"is_system_spawned"`
}

type Task struct {
	ID                uuid.UUID                 `json:"id"`
	TeamID            uuid.UUID                 `json:"team_id"`
	Title             string                    `json:"title"`
	Description       sql.NullString            `json:"description"`
	Status            NullTaskStatus            `json:"status"`
	FulfillmentStatus NullTaskFulfillmentStatus `json:"fulfillment_status"`
	ReviewStatus      TaskReviewStatus          `json:"review_status"`
	CreatedBy         uuid.UUID                 `json:"created_by"`
	DueDate           sql.NullTime              `json:"due_date"`
	CreatedAt         sql.NullTime              `json:"created_at"`
}

type TaskParticipant struct {
	TaskID uuid.UUID       `json:"task_id"`
	UserID uuid.UUID       `json:"user_id"`
	Role   ParticipantRole `json:"role"`
}

type TaskUpdate struct {
	ID        uuid.UUID     `json:"id"`
	TaskID    uuid.UUID     `json:"task_id"`
	UserID    uuid.NullUUID `json:"user_id"`
	Content   string        `json:"content"`
	CreatedAt sql.NullTime  `json:"created_at"`
}

type TaskUpdateComment struct {
	ID           uuid.UUID     `json:"id"`
	TaskUpdateID uuid.UUID     `json:"task_update_id"`
	UserID       uuid.NullUUID `json:"user_id"`
	Content      string        `json:"content"`
	CreatedAt    sql.NullTime  `json:"created_at"`
}

type Team struct {
	ID        uuid.UUID    `json:"id"`
	OrgID     uuid.UUID    `json:"org_id"`
	Name      string       `json:"name"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type TeamLeaderboardSetting struct {
	TeamID             uuid.UUID     `json:"team_id"`
	LeaderboardVisible bool          `json:"leaderboard_visible"`
	UpdatedBy          uuid.NullUUID `json:"updated_by"`
	UpdatedAt          sql.NullTime  `json:"updated_at"`
}

type TeamMember struct {
	TeamID   uuid.UUID    `json:"team_id"`
	UserID   uuid.UUID    `json:"user_id"`
	TeamRole TeamRoleEnum `json:"team_role"`
	JoinedAt sql.NullTime `json:"joined_at"`
}

type Transcription struct {
	ID             uuid.UUID               `json:"id"`
	AttachmentID   uuid.UUID               `json:"attachment_id"`
	Status         NullTranscriptionStatus `json:"status"`
	TranscriptText sql.NullString          `json:"transcript_text"`
	ErrorMessage   sql.NullString          `json:"error_message"`
	CreatedAt      sql.NullTime            `json:"created_at"`
	UpdatedAt      sql.NullTime            `json:"updated_at"`
}

type User struct {
	ID          uuid.UUID      `json:"id"`
	OrgID       uuid.UUID      `json:"org_id"`
	Status      NullUserStatus `json:"status"`
	FirstName   sql.NullString `json:"first_name"`
	LastName    sql.NullString `json:"last_name"`
	EmailID     string         `json:"email_id"`
	FaceS3Uri   sql.NullString `json:"face_s3_uri"`
	PhoneNumber sql.NullString `json:"phone_number"`
	CreatedAt   sql.NullTime   `json:"created_at"`
}

type UserCredential struct {
	UserID       uuid.UUID    `json:"user_id"`
	PasswordHash string       `json:"password_hash"`
	UpdatedAt    sql.NullTime `json:"updated_at"`
}

type UserSystemRole struct {
	UserID    uuid.UUID    `json:"user_id"`
	OrgID     uuid.UUID    `json:"org_id"`
	Role      SystemRole   `json:"role"`
	GrantedAt sql.NullTime `json:"granted_at"`
}
