// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const clearNotifications = `-- name: ClearNotifications :exec
DELETE FROM notifications WHERE user_id = $1 AND org_id = $2
`

type ClearNotificationsParams struct {
	UserID uuid.UUID `json:"user_id"`
	OrgID  uuid.UUID `json:"org_id"`
}

func (q *Queries) ClearNotifications(ctx context.Context, arg ClearNotificationsParams) error {
	_, err := q.db.ExecContext(ctx, clearNotifications, arg.UserID, arg.OrgID)
	return err
}

const createNotification = `-- name: CreateNotification :exec
INSERT INTO notifications (user_id, org_id, title, message)
VALUES ($1, $2, $3, $4)
`

type CreateNotificationParams struct {
	UserID  uuid.UUID `json:"user_id"`
	OrgID   uuid.UUID `json:"org_id"`
	Title   string    `json:"title"`
	Message string    `json:"message"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) error {
	_, err := q.db.ExecContext(ctx, createNotification,
		arg.UserID,
		arg.OrgID,
		arg.Title,
		arg.Message,
	)
	return err
}

const getUserNotifications = `-- name: GetUserNotifications :many
SELECT id, title, message, is_read, created_at
FROM notifications
WHERE user_id = $1 AND org_id = $2
ORDER BY created_at DESC
LIMIT 20
`

type GetUserNotificationsParams struct {
	UserID uuid.UUID `json:"user_id"`
	OrgID  uuid.UUID `json:"org_id"`
}

type GetUserNotificationsRow struct {
	ID        uuid.UUID    `json:"id"`
	Title     string       `json:"title"`
	Message   string       `json:"message"`
	IsRead    sql.NullBool `json:"is_read"`
	CreatedAt sql.NullTime `json:"created_at"`
}

func (q *Queries) GetUserNotifications(ctx context.Context, arg GetUserNotificationsParams) ([]GetUserNotificationsRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserNotifications, arg.UserID, arg.OrgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserNotificationsRow
	for rows.Next() {
		var i GetUserNotificationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Message,
			&i.IsRead,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNotificationsRead = `-- name: MarkNotificationsRead :exec
UPDATE notifications SET is_read = TRUE WHERE user_id = $1 AND org_id = $2
`

type MarkNotificationsReadParams struct {
	UserID uuid.UUID `json:"user_id"`
	OrgID  uuid.UUID `json:"org_id"`
}

func (q *Queries) MarkNotificationsRead(ctx context.Context, arg MarkNotificationsReadParams) error {
	_, err := q.db.ExecContext(ctx, markNotificationsRead, arg.UserID, arg.OrgID)
	return err
}

const markOneNotificationRead = `-- name: MarkOneNotificationRead :exec
UPDATE notifications SET is_read = TRUE WHERE id = $1 AND user_id = $2 AND org_id = $3
`

type MarkOneNotificationReadParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
	OrgID  uuid.UUID `json:"org_id"`
}

func (q *Queries) MarkOneNotificationRead(ctx context.Context, arg MarkOneNotificationReadParams) error {
	_, err := q.db.ExecContext(ctx, markOneNotificationRead, arg.ID, arg.UserID, arg.OrgID)
	return err
}
