// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: organisation.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createOrganizations = `-- name: CreateOrganizations :one
INSERT INTO organizations (
    name, domain
) VALUES (
    $1, $2
)
RETURNING id, name, domain, created_at
`

type CreateOrganizationsParams struct {
	Name   string         `json:"name"`
	Domain sql.NullString `json:"domain"`
}

func (q *Queries) CreateOrganizations(ctx context.Context, arg CreateOrganizationsParams) (Organization, error) {
	row := q.db.QueryRowContext(ctx, createOrganizations, arg.Name, arg.Domain)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Domain,
		&i.CreatedAt,
	)
	return i, err
}

const getOrganizationName = `-- name: GetOrganizationName :one
SELECT name FROM organizations 
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetOrganizationName(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRowContext(ctx, getOrganizationName, id)
	var name string
	err := row.Scan(&name)
	return name, err
}
