// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: organisation.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createOrganizations = `-- name: CreateOrganizations :one
INSERT INTO organizations (
    name, domain
) VALUES (
    $1, $2
)
RETURNING id, name, domain, attendance_enabled, created_at
`

type CreateOrganizationsParams struct {
	Name   string         `json:"name"`
	Domain sql.NullString `json:"domain"`
}

func (q *Queries) CreateOrganizations(ctx context.Context, arg CreateOrganizationsParams) (Organization, error) {
	row := q.db.QueryRowContext(ctx, createOrganizations, arg.Name, arg.Domain)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Domain,
		&i.AttendanceEnabled,
		&i.CreatedAt,
	)
	return i, err
}

const deleteOrganization = `-- name: DeleteOrganization :exec
DELETE FROM organizations WHERE id = $1
`

func (q *Queries) DeleteOrganization(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteOrganization, id)
	return err
}

const getOrgInfo = `-- name: GetOrgInfo :one
SELECT name, attendance_enabled FROM organizations
WHERE id = $1 LIMIT 1
`

type GetOrgInfoRow struct {
	Name              string `json:"name"`
	AttendanceEnabled bool   `json:"attendance_enabled"`
}

func (q *Queries) GetOrgInfo(ctx context.Context, id uuid.UUID) (GetOrgInfoRow, error) {
	row := q.db.QueryRowContext(ctx, getOrgInfo, id)
	var i GetOrgInfoRow
	err := row.Scan(&i.Name, &i.AttendanceEnabled)
	return i, err
}

const getOrganizationName = `-- name: GetOrganizationName :one
SELECT name FROM organizations
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetOrganizationName(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRowContext(ctx, getOrganizationName, id)
	var name string
	err := row.Scan(&name)
	return name, err
}

const setOrgAttendanceEnabled = `-- name: SetOrgAttendanceEnabled :exec
UPDATE organizations SET attendance_enabled = $2 WHERE id = $1
`

type SetOrgAttendanceEnabledParams struct {
	ID                uuid.UUID `json:"id"`
	AttendanceEnabled bool      `json:"attendance_enabled"`
}

func (q *Queries) SetOrgAttendanceEnabled(ctx context.Context, arg SetOrgAttendanceEnabledParams) error {
	_, err := q.db.ExecContext(ctx, setOrgAttendanceEnabled, arg.ID, arg.AttendanceEnabled)
	return err
}
