// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateInvitedUser(ctx context.Context, arg CreateInvitedUserParams) (User, error)
	CreateOrganizations(ctx context.Context, arg CreateOrganizationsParams) (Organization, error)
	CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateUserCredentials(ctx context.Context, arg CreateUserCredentialsParams) (UserCredential, error)
	GetTaskByID(ctx context.Context, id uuid.UUID) (Task, error)
	GetUserByEmail(ctx context.Context, emailID string) (User, error)
	GetUserCredentials(ctx context.Context, userID uuid.UUID) (UserCredential, error)
	ListTasksByTeam(ctx context.Context, teamID uuid.UUID) ([]Task, error)
	UpdateUserOnboarding(ctx context.Context, arg UpdateUserOnboardingParams) (User, error)
}

var _ Querier = (*Queries)(nil)
