// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scores.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const getAggregatedLeaderboard = `-- name: GetAggregatedLeaderboard :many
SELECT
    u.id AS user_id,
    u.first_name,
    u.last_name,
    u.email_id,
    COALESCE(SUM(es.points_awarded), 0)::bigint AS total_points,
    COUNT(es.id) FILTER (WHERE es.event_type = 'ON_TIME_COMPLETION') AS on_time_count,
    COUNT(es.id) FILTER (WHERE es.event_type IN ('ON_TIME_COMPLETION', 'LATE_COMPLETION')) AS completed_count
FROM team_members tm
JOIN users u ON tm.user_id = u.id
LEFT JOIN employee_scores es ON u.id = es.user_id AND es.superseded = false
WHERE tm.team_id = ANY($1::uuid[])
GROUP BY u.id, u.first_name, u.last_name, u.email_id
ORDER BY total_points DESC, u.first_name ASC
`

type GetAggregatedLeaderboardRow struct {
	UserID         uuid.UUID      `json:"user_id"`
	FirstName      sql.NullString `json:"first_name"`
	LastName       sql.NullString `json:"last_name"`
	EmailID        string         `json:"email_id"`
	TotalPoints    int64          `json:"total_points"`
	OnTimeCount    int64          `json:"on_time_count"`
	CompletedCount int64          `json:"completed_count"`
}

func (q *Queries) GetAggregatedLeaderboard(ctx context.Context, dollar_1 []uuid.UUID) ([]GetAggregatedLeaderboardRow, error) {
	rows, err := q.db.QueryContext(ctx, getAggregatedLeaderboard, pq.Array(dollar_1))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAggregatedLeaderboardRow
	for rows.Next() {
		var i GetAggregatedLeaderboardRow
		if err := rows.Scan(
			&i.UserID,
			&i.FirstName,
			&i.LastName,
			&i.EmailID,
			&i.TotalPoints,
			&i.OnTimeCount,
			&i.CompletedCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBulkUserScoreBreakdowns = `-- name: GetBulkUserScoreBreakdowns :many
SELECT
    u.id AS user_id,
    u.first_name,
    u.last_name,
    u.email_id,
    COALESCE(SUM(es.points_awarded), 0)::bigint AS total_points,
    COUNT(es.id) FILTER (WHERE es.event_type = 'ON_TIME_COMPLETION') AS on_time_count,
    COUNT(es.id) FILTER (WHERE es.event_type = 'LATE_COMPLETION') AS late_count,
    COUNT(es.id) FILTER (WHERE es.event_type = 'MISSED_DEADLINE') AS missed_count,
    COUNT(es.id) FILTER (WHERE es.event_type = 'REJECTION') AS rejection_count
FROM team_members tm_member
JOIN users u ON tm_member.user_id = u.id
LEFT JOIN employee_scores es ON u.id = es.user_id AND es.superseded = false
WHERE tm_member.team_id = ANY($1::uuid[])
GROUP BY u.id, u.first_name, u.last_name, u.email_id
ORDER BY total_points DESC
`

type GetBulkUserScoreBreakdownsRow struct {
	UserID         uuid.UUID      `json:"user_id"`
	FirstName      sql.NullString `json:"first_name"`
	LastName       sql.NullString `json:"last_name"`
	EmailID        string         `json:"email_id"`
	TotalPoints    int64          `json:"total_points"`
	OnTimeCount    int64          `json:"on_time_count"`
	LateCount      int64          `json:"late_count"`
	MissedCount    int64          `json:"missed_count"`
	RejectionCount int64          `json:"rejection_count"`
}

func (q *Queries) GetBulkUserScoreBreakdowns(ctx context.Context, dollar_1 []uuid.UUID) ([]GetBulkUserScoreBreakdownsRow, error) {
	rows, err := q.db.QueryContext(ctx, getBulkUserScoreBreakdowns, pq.Array(dollar_1))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetBulkUserScoreBreakdownsRow
	for rows.Next() {
		var i GetBulkUserScoreBreakdownsRow
		if err := rows.Scan(
			&i.UserID,
			&i.FirstName,
			&i.LastName,
			&i.EmailID,
			&i.TotalPoints,
			&i.OnTimeCount,
			&i.LateCount,
			&i.MissedCount,
			&i.RejectionCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLeaderboardVisibility = `-- name: GetLeaderboardVisibility :one
SELECT leaderboard_visible FROM team_leaderboard_settings
WHERE team_id = $1
`

func (q *Queries) GetLeaderboardVisibility(ctx context.Context, teamID uuid.UUID) (bool, error) {
	row := q.db.QueryRowContext(ctx, getLeaderboardVisibility, teamID)
	var leaderboard_visible bool
	err := row.Scan(&leaderboard_visible)
	return leaderboard_visible, err
}

const getLeaderboardVisibilityBulk = `-- name: GetLeaderboardVisibilityBulk :many
SELECT team_id, leaderboard_visible
FROM team_leaderboard_settings
WHERE team_id = ANY($1::uuid[])
`

type GetLeaderboardVisibilityBulkRow struct {
	TeamID             uuid.UUID `json:"team_id"`
	LeaderboardVisible bool      `json:"leaderboard_visible"`
}

func (q *Queries) GetLeaderboardVisibilityBulk(ctx context.Context, dollar_1 []uuid.UUID) ([]GetLeaderboardVisibilityBulkRow, error) {
	rows, err := q.db.QueryContext(ctx, getLeaderboardVisibilityBulk, pq.Array(dollar_1))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLeaderboardVisibilityBulkRow
	for rows.Next() {
		var i GetLeaderboardVisibilityBulkRow
		if err := rows.Scan(&i.TeamID, &i.LeaderboardVisible); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMissedDeadlineCandidates = `-- name: GetMissedDeadlineCandidates :many
SELECT t.id AS task_id, t.team_id, t.due_date, tm.org_id, tp.user_id
FROM tasks t
JOIN teams tm ON t.team_id = tm.id
JOIN task_participants tp ON t.id = tp.task_id AND tp.role = 'ASSIGNEE'
WHERE t.due_date < NOW()
  AND t.status = 'OPEN'
  AND t.review_status != 'APPROVED'
  AND t.due_date IS NOT NULL
  AND NOT EXISTS (
      SELECT 1 FROM employee_scores es
      WHERE es.task_id = t.id AND es.user_id = tp.user_id
        AND es.event_type = 'MISSED_DEADLINE' AND es.superseded = false
  )
`

type GetMissedDeadlineCandidatesRow struct {
	TaskID  uuid.UUID    `json:"task_id"`
	TeamID  uuid.UUID    `json:"team_id"`
	DueDate sql.NullTime `json:"due_date"`
	OrgID   uuid.UUID    `json:"org_id"`
	UserID  uuid.UUID    `json:"user_id"`
}

func (q *Queries) GetMissedDeadlineCandidates(ctx context.Context) ([]GetMissedDeadlineCandidatesRow, error) {
	rows, err := q.db.QueryContext(ctx, getMissedDeadlineCandidates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMissedDeadlineCandidatesRow
	for rows.Next() {
		var i GetMissedDeadlineCandidatesRow
		if err := rows.Scan(
			&i.TaskID,
			&i.TeamID,
			&i.DueDate,
			&i.OrgID,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTaskAssigneesWithContext = `-- name: GetTaskAssigneesWithContext :many
SELECT tp.user_id, t.team_id, tm.org_id
FROM task_participants tp
JOIN tasks t ON tp.task_id = t.id
JOIN teams tm ON t.team_id = tm.id
WHERE tp.task_id = $1 AND tp.role = 'ASSIGNEE'
`

type GetTaskAssigneesWithContextRow struct {
	UserID uuid.UUID `json:"user_id"`
	TeamID uuid.UUID `json:"team_id"`
	OrgID  uuid.UUID `json:"org_id"`
}

func (q *Queries) GetTaskAssigneesWithContext(ctx context.Context, taskID uuid.UUID) ([]GetTaskAssigneesWithContextRow, error) {
	rows, err := q.db.QueryContext(ctx, getTaskAssigneesWithContext, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTaskAssigneesWithContextRow
	for rows.Next() {
		var i GetTaskAssigneesWithContextRow
		if err := rows.Scan(&i.UserID, &i.TeamID, &i.OrgID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTeamLeaderboard = `-- name: GetTeamLeaderboard :many
SELECT
    u.id AS user_id,
    u.first_name,
    u.last_name,
    u.email_id,
    COALESCE(SUM(es.points_awarded), 0)::bigint AS total_points,
    COUNT(es.id) FILTER (WHERE es.event_type = 'ON_TIME_COMPLETION') AS on_time_count,
    COUNT(es.id) FILTER (WHERE es.event_type IN ('ON_TIME_COMPLETION', 'LATE_COMPLETION')) AS completed_count
FROM team_members tm
JOIN users u ON tm.user_id = u.id
LEFT JOIN employee_scores es ON u.id = es.user_id AND es.team_id = tm.team_id AND es.superseded = false
WHERE tm.team_id = $1
GROUP BY u.id, u.first_name, u.last_name, u.email_id
ORDER BY total_points DESC, u.first_name ASC
`

type GetTeamLeaderboardRow struct {
	UserID         uuid.UUID      `json:"user_id"`
	FirstName      sql.NullString `json:"first_name"`
	LastName       sql.NullString `json:"last_name"`
	EmailID        string         `json:"email_id"`
	TotalPoints    int64          `json:"total_points"`
	OnTimeCount    int64          `json:"on_time_count"`
	CompletedCount int64          `json:"completed_count"`
}

func (q *Queries) GetTeamLeaderboard(ctx context.Context, teamID uuid.UUID) ([]GetTeamLeaderboardRow, error) {
	rows, err := q.db.QueryContext(ctx, getTeamLeaderboard, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTeamLeaderboardRow
	for rows.Next() {
		var i GetTeamLeaderboardRow
		if err := rows.Scan(
			&i.UserID,
			&i.FirstName,
			&i.LastName,
			&i.EmailID,
			&i.TotalPoints,
			&i.OnTimeCount,
			&i.CompletedCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserScoreBreakdown = `-- name: GetUserScoreBreakdown :one
SELECT
    COALESCE(SUM(points_awarded), 0)::bigint AS total_points,
    COUNT(*) FILTER (WHERE event_type = 'ON_TIME_COMPLETION') AS on_time_count,
    COUNT(*) FILTER (WHERE event_type = 'LATE_COMPLETION') AS late_count,
    COUNT(*) FILTER (WHERE event_type = 'MISSED_DEADLINE') AS missed_count,
    COUNT(*) FILTER (WHERE event_type = 'REJECTION') AS rejection_count
FROM employee_scores
WHERE user_id = $1 AND superseded = false
  AND ($2::text = '' OR team_id::text = $2)
`

type GetUserScoreBreakdownParams struct {
	UserID     uuid.UUID `json:"user_id"`
	TeamFilter string    `json:"team_filter"`
}

type GetUserScoreBreakdownRow struct {
	TotalPoints    int64 `json:"total_points"`
	OnTimeCount    int64 `json:"on_time_count"`
	LateCount      int64 `json:"late_count"`
	MissedCount    int64 `json:"missed_count"`
	RejectionCount int64 `json:"rejection_count"`
}

func (q *Queries) GetUserScoreBreakdown(ctx context.Context, arg GetUserScoreBreakdownParams) (GetUserScoreBreakdownRow, error) {
	row := q.db.QueryRowContext(ctx, getUserScoreBreakdown, arg.UserID, arg.TeamFilter)
	var i GetUserScoreBreakdownRow
	err := row.Scan(
		&i.TotalPoints,
		&i.OnTimeCount,
		&i.LateCount,
		&i.MissedCount,
		&i.RejectionCount,
	)
	return i, err
}

const getUserScoreEvents = `-- name: GetUserScoreEvents :many
SELECT
    es.id, es.task_id, es.team_id, es.event_type::text, es.points_awarded,
    es.due_date_snapshot, es.event_at,
    t.title AS task_title,
    tm.name AS team_name
FROM employee_scores es
JOIN tasks t ON es.task_id = t.id
JOIN teams tm ON es.team_id = tm.id
WHERE es.user_id = $1 AND es.superseded = false
  AND ($4::text = '' OR es.team_id::text = $4)
ORDER BY es.event_at DESC
LIMIT $2 OFFSET $3
`

type GetUserScoreEventsParams struct {
	UserID     uuid.UUID `json:"user_id"`
	Limit      int32     `json:"limit"`
	Offset     int32     `json:"offset"`
	TeamFilter string    `json:"team_filter"`
}

type GetUserScoreEventsRow struct {
	ID              uuid.UUID    `json:"id"`
	TaskID          uuid.UUID    `json:"task_id"`
	TeamID          uuid.UUID    `json:"team_id"`
	EsEventType     string       `json:"es_event_type"`
	PointsAwarded   int32        `json:"points_awarded"`
	DueDateSnapshot sql.NullTime `json:"due_date_snapshot"`
	EventAt         time.Time    `json:"event_at"`
	TaskTitle       string       `json:"task_title"`
	TeamName        string       `json:"team_name"`
}

func (q *Queries) GetUserScoreEvents(ctx context.Context, arg GetUserScoreEventsParams) ([]GetUserScoreEventsRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserScoreEvents,
		arg.UserID,
		arg.Limit,
		arg.Offset,
		arg.TeamFilter,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserScoreEventsRow
	for rows.Next() {
		var i GetUserScoreEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.TeamID,
			&i.EsEventType,
			&i.PointsAwarded,
			&i.DueDateSnapshot,
			&i.EventAt,
			&i.TaskTitle,
			&i.TeamName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserScoreReportData = `-- name: GetUserScoreReportData :many
SELECT
    es.event_type::text, es.points_awarded, es.due_date_snapshot, es.event_at,
    t.title AS task_title,
    tm.name AS team_name
FROM employee_scores es
JOIN tasks t ON es.task_id = t.id
JOIN teams tm ON es.team_id = tm.id
WHERE es.user_id = $1 AND es.superseded = false
ORDER BY es.event_at DESC
`

type GetUserScoreReportDataRow struct {
	EsEventType     string       `json:"es_event_type"`
	PointsAwarded   int32        `json:"points_awarded"`
	DueDateSnapshot sql.NullTime `json:"due_date_snapshot"`
	EventAt         time.Time    `json:"event_at"`
	TaskTitle       string       `json:"task_title"`
	TeamName        string       `json:"team_name"`
}

func (q *Queries) GetUserScoreReportData(ctx context.Context, userID uuid.UUID) ([]GetUserScoreReportDataRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserScoreReportData, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserScoreReportDataRow
	for rows.Next() {
		var i GetUserScoreReportDataRow
		if err := rows.Scan(
			&i.EsEventType,
			&i.PointsAwarded,
			&i.DueDateSnapshot,
			&i.EventAt,
			&i.TaskTitle,
			&i.TeamName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertScoreEvent = `-- name: InsertScoreEvent :one
INSERT INTO employee_scores (task_id, user_id, team_id, org_id, event_type, points_awarded, due_date_snapshot, event_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, task_id, user_id, team_id, org_id, event_type, points_awarded, due_date_snapshot, event_at, superseded, created_at
`

type InsertScoreEventParams struct {
	TaskID          uuid.UUID      `json:"task_id"`
	UserID          uuid.UUID      `json:"user_id"`
	TeamID          uuid.UUID      `json:"team_id"`
	OrgID           uuid.UUID      `json:"org_id"`
	EventType       ScoreEventType `json:"event_type"`
	PointsAwarded   int32          `json:"points_awarded"`
	DueDateSnapshot sql.NullTime   `json:"due_date_snapshot"`
	EventAt         time.Time      `json:"event_at"`
}

func (q *Queries) InsertScoreEvent(ctx context.Context, arg InsertScoreEventParams) (EmployeeScore, error) {
	row := q.db.QueryRowContext(ctx, insertScoreEvent,
		arg.TaskID,
		arg.UserID,
		arg.TeamID,
		arg.OrgID,
		arg.EventType,
		arg.PointsAwarded,
		arg.DueDateSnapshot,
		arg.EventAt,
	)
	var i EmployeeScore
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.UserID,
		&i.TeamID,
		&i.OrgID,
		&i.EventType,
		&i.PointsAwarded,
		&i.DueDateSnapshot,
		&i.EventAt,
		&i.Superseded,
		&i.CreatedAt,
	)
	return i, err
}

const supersedeScoreEvents = `-- name: SupersedeScoreEvents :exec
UPDATE employee_scores
SET superseded = true
WHERE task_id = $1 AND user_id = $2 AND superseded = false
`

type SupersedeScoreEventsParams struct {
	TaskID uuid.UUID `json:"task_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) SupersedeScoreEvents(ctx context.Context, arg SupersedeScoreEventsParams) error {
	_, err := q.db.ExecContext(ctx, supersedeScoreEvents, arg.TaskID, arg.UserID)
	return err
}

const upsertLeaderboardVisibility = `-- name: UpsertLeaderboardVisibility :exec
INSERT INTO team_leaderboard_settings (team_id, leaderboard_visible, updated_by, updated_at)
VALUES ($1, $2, $3, NOW())
ON CONFLICT (team_id) DO UPDATE SET leaderboard_visible = $2, updated_by = $3, updated_at = NOW()
`

type UpsertLeaderboardVisibilityParams struct {
	TeamID             uuid.UUID     `json:"team_id"`
	LeaderboardVisible bool          `json:"leaderboard_visible"`
	UpdatedBy          uuid.NullUUID `json:"updated_by"`
}

func (q *Queries) UpsertLeaderboardVisibility(ctx context.Context, arg UpsertLeaderboardVisibilityParams) error {
	_, err := q.db.ExecContext(ctx, upsertLeaderboardVisibility, arg.TeamID, arg.LeaderboardVisible, arg.UpdatedBy)
	return err
}
