// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: task.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const addTaskParticipant = `-- name: AddTaskParticipant :exec
INSERT INTO task_participants (task_id, user_id, role)
VALUES ($1, $2, $3)
ON CONFLICT (task_id, user_id, role) DO NOTHING
`

type AddTaskParticipantParams struct {
	TaskID uuid.UUID       `json:"task_id"`
	UserID uuid.UUID       `json:"user_id"`
	Role   ParticipantRole `json:"role"`
}

func (q *Queries) AddTaskParticipant(ctx context.Context, arg AddTaskParticipantParams) error {
	_, err := q.db.ExecContext(ctx, addTaskParticipant, arg.TaskID, arg.UserID, arg.Role)
	return err
}

const addTaskUpdate = `-- name: AddTaskUpdate :one
INSERT INTO task_updates (task_id, user_id, content)
VALUES ($1, $2, $3)
RETURNING id, task_id, user_id, content, created_at
`

type AddTaskUpdateParams struct {
	TaskID  uuid.UUID     `json:"task_id"`
	UserID  uuid.NullUUID `json:"user_id"`
	Content string        `json:"content"`
}

func (q *Queries) AddTaskUpdate(ctx context.Context, arg AddTaskUpdateParams) (TaskUpdate, error) {
	row := q.db.QueryRowContext(ctx, addTaskUpdate, arg.TaskID, arg.UserID, arg.Content)
	var i TaskUpdate
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.UserID,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const addUpdateComment = `-- name: AddUpdateComment :one
INSERT INTO task_update_comments (task_update_id, user_id, content)
VALUES ($1, $2, $3) RETURNING id
`

type AddUpdateCommentParams struct {
	TaskUpdateID uuid.UUID     `json:"task_update_id"`
	UserID       uuid.NullUUID `json:"user_id"`
	Content      string        `json:"content"`
}

func (q *Queries) AddUpdateComment(ctx context.Context, arg AddUpdateCommentParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, addUpdateComment, arg.TaskUpdateID, arg.UserID, arg.Content)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const approveTaskState = `-- name: ApproveTaskState :exec
UPDATE tasks SET status = 'CLOSED', review_status = 'APPROVED' WHERE id = $1
`

func (q *Queries) ApproveTaskState(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, approveTaskState, id)
	return err
}

const completeReminder = `-- name: CompleteReminder :exec
UPDATE reminders 
SET status = 'SENT' 
WHERE id = $1
`

func (q *Queries) CompleteReminder(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, completeReminder, id)
	return err
}

const createReminder = `-- name: CreateReminder :one
INSERT INTO reminders (task_id, scheduled_at, channel, recurrence_value, recurrence_unit, is_system_spawned)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, task_id, scheduled_at, channel, status, recurrence_value, recurrence_unit, created_at, is_system_spawned
`

type CreateReminderParams struct {
	TaskID          uuid.UUID          `json:"task_id"`
	ScheduledAt     time.Time          `json:"scheduled_at"`
	Channel         ReminderChannel    `json:"channel"`
	RecurrenceValue sql.NullInt32      `json:"recurrence_value"`
	RecurrenceUnit  NullRecurrenceUnit `json:"recurrence_unit"`
	IsSystemSpawned bool               `json:"is_system_spawned"`
}

func (q *Queries) CreateReminder(ctx context.Context, arg CreateReminderParams) (Reminder, error) {
	row := q.db.QueryRowContext(ctx, createReminder,
		arg.TaskID,
		arg.ScheduledAt,
		arg.Channel,
		arg.RecurrenceValue,
		arg.RecurrenceUnit,
		arg.IsSystemSpawned,
	)
	var i Reminder
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.ScheduledAt,
		&i.Channel,
		&i.Status,
		&i.RecurrenceValue,
		&i.RecurrenceUnit,
		&i.CreatedAt,
		&i.IsSystemSpawned,
	)
	return i, err
}

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (team_id, title, description, created_by, due_date)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, team_id, title, description, status, fulfillment_status, review_status, created_by, due_date, created_at
`

type CreateTaskParams struct {
	TeamID      uuid.UUID      `json:"team_id"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	CreatedBy   uuid.UUID      `json:"created_by"`
	DueDate     sql.NullTime   `json:"due_date"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, createTask,
		arg.TeamID,
		arg.Title,
		arg.Description,
		arg.CreatedBy,
		arg.DueDate,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.FulfillmentStatus,
		&i.ReviewStatus,
		&i.CreatedBy,
		&i.DueDate,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAttachmentsByIDs = `-- name: DeleteAttachmentsByIDs :many
DELETE FROM attachments WHERE id = ANY($1::uuid[])
RETURNING file_url
`

func (q *Queries) DeleteAttachmentsByIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, deleteAttachmentsByIDs, pq.Array(dollar_1))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var file_url string
		if err := rows.Scan(&file_url); err != nil {
			return nil, err
		}
		items = append(items, file_url)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteTaskAttachments = `-- name: DeleteTaskAttachments :exec
DELETE FROM attachments WHERE task_id = $1 AND task_update_id IS NULL
`

func (q *Queries) DeleteTaskAttachments(ctx context.Context, taskID uuid.NullUUID) error {
	_, err := q.db.ExecContext(ctx, deleteTaskAttachments, taskID)
	return err
}

const deleteTaskParticipants = `-- name: DeleteTaskParticipants :exec
DELETE FROM task_participants WHERE task_id = $1
`

func (q *Queries) DeleteTaskParticipants(ctx context.Context, taskID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteTaskParticipants, taskID)
	return err
}

const deleteTaskReminders = `-- name: DeleteTaskReminders :exec
DELETE FROM reminders WHERE task_id = $1
`

func (q *Queries) DeleteTaskReminders(ctx context.Context, taskID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteTaskReminders, taskID)
	return err
}

const getAdminAllTasks = `-- name: GetAdminAllTasks :many
WITH base AS (
    SELECT DISTINCT
        t.id, t.team_id, t.title, t.description, t.status, t.fulfillment_status, t.review_status,
        t.created_by, t.due_date, t.created_at,
        u.first_name, u.last_name,
        tm.name AS team_name
    FROM tasks t
    JOIN users u ON t.created_by = u.id
    JOIN teams tm ON t.team_id = tm.id
    JOIN team_members tmem ON tm.id = tmem.team_id
    WHERE tmem.user_id = $1 AND tmem.team_role = 'TEAM_ADMIN'
)
SELECT id, team_id, title, description, status, fulfillment_status, review_status, created_by, due_date, created_at, first_name, last_name, team_name, COUNT(*) OVER() AS total_count
FROM base
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetAdminAllTasksParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

type GetAdminAllTasksRow struct {
	ID                uuid.UUID                 `json:"id"`
	TeamID            uuid.UUID                 `json:"team_id"`
	Title             string                    `json:"title"`
	Description       sql.NullString            `json:"description"`
	Status            NullTaskStatus            `json:"status"`
	FulfillmentStatus NullTaskFulfillmentStatus `json:"fulfillment_status"`
	ReviewStatus      TaskReviewStatus          `json:"review_status"`
	CreatedBy         uuid.UUID                 `json:"created_by"`
	DueDate           sql.NullTime              `json:"due_date"`
	CreatedAt         sql.NullTime              `json:"created_at"`
	FirstName         sql.NullString            `json:"first_name"`
	LastName          sql.NullString            `json:"last_name"`
	TeamName          string                    `json:"team_name"`
	TotalCount        int64                     `json:"total_count"`
}

func (q *Queries) GetAdminAllTasks(ctx context.Context, arg GetAdminAllTasksParams) ([]GetAdminAllTasksRow, error) {
	rows, err := q.db.QueryContext(ctx, getAdminAllTasks, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAdminAllTasksRow
	for rows.Next() {
		var i GetAdminAllTasksRow
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.FulfillmentStatus,
			&i.ReviewStatus,
			&i.CreatedBy,
			&i.DueDate,
			&i.CreatedAt,
			&i.FirstName,
			&i.LastName,
			&i.TeamName,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDueReminders = `-- name: GetDueReminders :many
SELECT r.id, r.task_id, r.channel, r.recurrence_value, r.recurrence_unit, t.title as task_title
FROM reminders r
JOIN tasks t ON r.task_id = t.id
WHERE r.status = 'PENDING' 
  AND r.scheduled_at <= NOW()
FOR UPDATE SKIP LOCKED
`

type GetDueRemindersRow struct {
	ID              uuid.UUID          `json:"id"`
	TaskID          uuid.UUID          `json:"task_id"`
	Channel         ReminderChannel    `json:"channel"`
	RecurrenceValue sql.NullInt32      `json:"recurrence_value"`
	RecurrenceUnit  NullRecurrenceUnit `json:"recurrence_unit"`
	TaskTitle       string             `json:"task_title"`
}

func (q *Queries) GetDueReminders(ctx context.Context) ([]GetDueRemindersRow, error) {
	rows, err := q.db.QueryContext(ctx, getDueReminders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDueRemindersRow
	for rows.Next() {
		var i GetDueRemindersRow
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.Channel,
			&i.RecurrenceValue,
			&i.RecurrenceUnit,
			&i.TaskTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEmployeeTasks = `-- name: GetEmployeeTasks :many
WITH distinct_tasks AS (
    SELECT DISTINCT 
        t.id, t.team_id, t.title, t.description, t.status, 
        t.fulfillment_status, t.review_status, t.created_by, 
        t.due_date, t.created_at, u.first_name, u.last_name
    FROM tasks t
    JOIN users u ON t.created_by = u.id
    JOIN task_participants tp ON t.id = tp.task_id
    WHERE t.team_id = $1 AND tp.user_id = $2
)
SELECT 
    id, team_id, title, description, status, fulfillment_status, review_status, created_by, due_date, created_at, first_name, last_name, 
    COUNT(*) OVER() AS total_count
FROM distinct_tasks
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type GetEmployeeTasksParams struct {
	TeamID uuid.UUID `json:"team_id"`
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

type GetEmployeeTasksRow struct {
	ID                uuid.UUID                 `json:"id"`
	TeamID            uuid.UUID                 `json:"team_id"`
	Title             string                    `json:"title"`
	Description       sql.NullString            `json:"description"`
	Status            NullTaskStatus            `json:"status"`
	FulfillmentStatus NullTaskFulfillmentStatus `json:"fulfillment_status"`
	ReviewStatus      TaskReviewStatus          `json:"review_status"`
	CreatedBy         uuid.UUID                 `json:"created_by"`
	DueDate           sql.NullTime              `json:"due_date"`
	CreatedAt         sql.NullTime              `json:"created_at"`
	FirstName         sql.NullString            `json:"first_name"`
	LastName          sql.NullString            `json:"last_name"`
	TotalCount        int64                     `json:"total_count"`
}

func (q *Queries) GetEmployeeTasks(ctx context.Context, arg GetEmployeeTasksParams) ([]GetEmployeeTasksRow, error) {
	rows, err := q.db.QueryContext(ctx, getEmployeeTasks,
		arg.TeamID,
		arg.UserID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEmployeeTasksRow
	for rows.Next() {
		var i GetEmployeeTasksRow
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.FulfillmentStatus,
			&i.ReviewStatus,
			&i.CreatedBy,
			&i.DueDate,
			&i.CreatedAt,
			&i.FirstName,
			&i.LastName,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTaskAssigneeEmails = `-- name: GetTaskAssigneeEmails :many
SELECT u.email_id
FROM users u
JOIN task_participants tp ON u.id = tp.user_id
WHERE tp.task_id = $1 AND tp.role = 'ASSIGNEE'
`

func (q *Queries) GetTaskAssigneeEmails(ctx context.Context, taskID uuid.UUID) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getTaskAssigneeEmails, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var email_id string
		if err := rows.Scan(&email_id); err != nil {
			return nil, err
		}
		items = append(items, email_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTaskAssigneePhones = `-- name: GetTaskAssigneePhones :many
SELECT u.phone_number 
FROM users u JOIN task_participants tp on u.id = tp.user_id
WHERE tp.task_id = $1 and tp.role = 'ASSIGNEE'
`

func (q *Queries) GetTaskAssigneePhones(ctx context.Context, taskID uuid.UUID) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getTaskAssigneePhones, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var phone_number string
		if err := rows.Scan(&phone_number); err != nil {
			return nil, err
		}
		items = append(items, phone_number)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTaskAttachments = `-- name: GetTaskAttachments :many
SELECT a.id, a.file_name, a.file_url, a.file_type, a.file_size_bytes,
       t.status AS transcription_status, t.transcript_text
FROM attachments a
LEFT JOIN transcriptions t ON t.attachment_id = a.id
WHERE a.task_id = $1 AND a.task_update_id IS NULL
`

type GetTaskAttachmentsRow struct {
	ID                  uuid.UUID               `json:"id"`
	FileName            string                  `json:"file_name"`
	FileUrl             string                  `json:"file_url"`
	FileType            string                  `json:"file_type"`
	FileSizeBytes       sql.NullInt64           `json:"file_size_bytes"`
	TranscriptionStatus NullTranscriptionStatus `json:"transcription_status"`
	TranscriptText      sql.NullString          `json:"transcript_text"`
}

func (q *Queries) GetTaskAttachments(ctx context.Context, taskID uuid.NullUUID) ([]GetTaskAttachmentsRow, error) {
	rows, err := q.db.QueryContext(ctx, getTaskAttachments, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTaskAttachmentsRow
	for rows.Next() {
		var i GetTaskAttachmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.FileName,
			&i.FileUrl,
			&i.FileType,
			&i.FileSizeBytes,
			&i.TranscriptionStatus,
			&i.TranscriptText,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTaskByID = `-- name: GetTaskByID :one
SELECT id, team_id, title, description, status, fulfillment_status, review_status, created_by, due_date, created_at FROM tasks
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTaskByID(ctx context.Context, id uuid.UUID) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTaskByID, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.FulfillmentStatus,
		&i.ReviewStatus,
		&i.CreatedBy,
		&i.DueDate,
		&i.CreatedAt,
	)
	return i, err
}

const getTaskCommentAttachments = `-- name: GetTaskCommentAttachments :many
SELECT a.id, a.task_comment_id, a.file_name, a.file_url, a.file_type, a.file_size_bytes,
       t.status AS transcription_status, t.transcript_text
FROM attachments a
LEFT JOIN transcriptions t ON t.attachment_id = a.id
WHERE a.task_comment_id = ANY($1::uuid[])
`

type GetTaskCommentAttachmentsRow struct {
	ID                  uuid.UUID               `json:"id"`
	TaskCommentID       uuid.NullUUID           `json:"task_comment_id"`
	FileName            string                  `json:"file_name"`
	FileUrl             string                  `json:"file_url"`
	FileType            string                  `json:"file_type"`
	FileSizeBytes       sql.NullInt64           `json:"file_size_bytes"`
	TranscriptionStatus NullTranscriptionStatus `json:"transcription_status"`
	TranscriptText      sql.NullString          `json:"transcript_text"`
}

func (q *Queries) GetTaskCommentAttachments(ctx context.Context, dollar_1 []uuid.UUID) ([]GetTaskCommentAttachmentsRow, error) {
	rows, err := q.db.QueryContext(ctx, getTaskCommentAttachments, pq.Array(dollar_1))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTaskCommentAttachmentsRow
	for rows.Next() {
		var i GetTaskCommentAttachmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.TaskCommentID,
			&i.FileName,
			&i.FileUrl,
			&i.FileType,
			&i.FileSizeBytes,
			&i.TranscriptionStatus,
			&i.TranscriptText,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTaskDetailsForNotifications = `-- name: GetTaskDetailsForNotifications :one
SELECT title FROM tasks WHERE id = $1
`

func (q *Queries) GetTaskDetailsForNotifications(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRowContext(ctx, getTaskDetailsForNotifications, id)
	var title string
	err := row.Scan(&title)
	return title, err
}

const getTaskParticipants = `-- name: GetTaskParticipants :many
SELECT tp.role::text, u.id, u.first_name, u.last_name, u.email_id
FROM task_participants tp
JOIN users u ON tp.user_id = u.id
WHERE tp.task_id = $1
`

type GetTaskParticipantsRow struct {
	TpRole    string         `json:"tp_role"`
	ID        uuid.UUID      `json:"id"`
	FirstName sql.NullString `json:"first_name"`
	LastName  sql.NullString `json:"last_name"`
	EmailID   string         `json:"email_id"`
}

func (q *Queries) GetTaskParticipants(ctx context.Context, taskID uuid.UUID) ([]GetTaskParticipantsRow, error) {
	rows, err := q.db.QueryContext(ctx, getTaskParticipants, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTaskParticipantsRow
	for rows.Next() {
		var i GetTaskParticipantsRow
		if err := rows.Scan(
			&i.TpRole,
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.EmailID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTaskReminders = `-- name: GetTaskReminders :many
SELECT id, task_id, scheduled_at, channel, status, recurrence_value, recurrence_unit, created_at, is_system_spawned FROM reminders
WHERE task_id = $1 AND is_system_spawned = FALSE ORDER BY scheduled_at ASC
`

func (q *Queries) GetTaskReminders(ctx context.Context, taskID uuid.UUID) ([]Reminder, error) {
	rows, err := q.db.QueryContext(ctx, getTaskReminders, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Reminder
	for rows.Next() {
		var i Reminder
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.ScheduledAt,
			&i.Channel,
			&i.Status,
			&i.RecurrenceValue,
			&i.RecurrenceUnit,
			&i.CreatedAt,
			&i.IsSystemSpawned,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTaskUpdateAttachments = `-- name: GetTaskUpdateAttachments :many
SELECT a.id, a.task_update_id, a.file_name, a.file_url, a.file_type, a.file_size_bytes,
       t.status AS transcription_status, t.transcript_text
FROM attachments a
LEFT JOIN transcriptions t ON t.attachment_id = a.id
WHERE a.task_update_id = ANY($1::uuid[])
`

type GetTaskUpdateAttachmentsRow struct {
	ID                  uuid.UUID               `json:"id"`
	TaskUpdateID        uuid.NullUUID           `json:"task_update_id"`
	FileName            string                  `json:"file_name"`
	FileUrl             string                  `json:"file_url"`
	FileType            string                  `json:"file_type"`
	FileSizeBytes       sql.NullInt64           `json:"file_size_bytes"`
	TranscriptionStatus NullTranscriptionStatus `json:"transcription_status"`
	TranscriptText      sql.NullString          `json:"transcript_text"`
}

func (q *Queries) GetTaskUpdateAttachments(ctx context.Context, dollar_1 []uuid.UUID) ([]GetTaskUpdateAttachmentsRow, error) {
	rows, err := q.db.QueryContext(ctx, getTaskUpdateAttachments, pq.Array(dollar_1))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTaskUpdateAttachmentsRow
	for rows.Next() {
		var i GetTaskUpdateAttachmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.TaskUpdateID,
			&i.FileName,
			&i.FileUrl,
			&i.FileType,
			&i.FileSizeBytes,
			&i.TranscriptionStatus,
			&i.TranscriptText,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTaskUpdateAuthor = `-- name: GetTaskUpdateAuthor :one
SELECT user_id FROM task_updates WHERE id = $1
`

func (q *Queries) GetTaskUpdateAuthor(ctx context.Context, id uuid.UUID) (uuid.NullUUID, error) {
	row := q.db.QueryRowContext(ctx, getTaskUpdateAuthor, id)
	var user_id uuid.NullUUID
	err := row.Scan(&user_id)
	return user_id, err
}

const getTaskUpdateComments = `-- name: GetTaskUpdateComments :many
SELECT c.id, c.task_update_id, c.user_id, c.content, c.created_at,
       u.first_name, u.last_name
FROM task_update_comments c
JOIN task_updates tu ON c.task_update_id = tu.id
LEFT JOIN users u ON c.user_id = u.id
WHERE tu.task_id = $1
ORDER BY c.created_at ASC
`

type GetTaskUpdateCommentsRow struct {
	ID           uuid.UUID      `json:"id"`
	TaskUpdateID uuid.UUID      `json:"task_update_id"`
	UserID       uuid.NullUUID  `json:"user_id"`
	Content      string         `json:"content"`
	CreatedAt    sql.NullTime   `json:"created_at"`
	FirstName    sql.NullString `json:"first_name"`
	LastName     sql.NullString `json:"last_name"`
}

func (q *Queries) GetTaskUpdateComments(ctx context.Context, taskID uuid.UUID) ([]GetTaskUpdateCommentsRow, error) {
	rows, err := q.db.QueryContext(ctx, getTaskUpdateComments, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTaskUpdateCommentsRow
	for rows.Next() {
		var i GetTaskUpdateCommentsRow
		if err := rows.Scan(
			&i.ID,
			&i.TaskUpdateID,
			&i.UserID,
			&i.Content,
			&i.CreatedAt,
			&i.FirstName,
			&i.LastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTaskUpdates = `-- name: GetTaskUpdates :many
SELECT tu.id, tu.task_id, tu.user_id, tu.content, tu.created_at,
       u.first_name, u.last_name,
       (SELECT COUNT(*) FROM task_update_comments c WHERE c.task_update_id = tu.id) AS comment_count
FROM task_updates tu
JOIN users u ON tu.user_id = u.id
WHERE tu.task_id = $1
ORDER BY tu.created_at DESC
LIMIT $2 OFFSET $3
`

type GetTaskUpdatesParams struct {
	TaskID uuid.UUID `json:"task_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

type GetTaskUpdatesRow struct {
	ID           uuid.UUID      `json:"id"`
	TaskID       uuid.UUID      `json:"task_id"`
	UserID       uuid.NullUUID  `json:"user_id"`
	Content      string         `json:"content"`
	CreatedAt    sql.NullTime   `json:"created_at"`
	FirstName    sql.NullString `json:"first_name"`
	LastName     sql.NullString `json:"last_name"`
	CommentCount int64          `json:"comment_count"`
}

func (q *Queries) GetTaskUpdates(ctx context.Context, arg GetTaskUpdatesParams) ([]GetTaskUpdatesRow, error) {
	rows, err := q.db.QueryContext(ctx, getTaskUpdates, arg.TaskID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTaskUpdatesRow
	for rows.Next() {
		var i GetTaskUpdatesRow
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.UserID,
			&i.Content,
			&i.CreatedAt,
			&i.FirstName,
			&i.LastName,
			&i.CommentCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTeamTasks = `-- name: GetTeamTasks :many
WITH base AS (
    SELECT t.id, t.team_id, t.title, t.description, t.status,
           t.fulfillment_status, t.review_status, t.created_by,
           t.due_date, t.created_at, u.first_name, u.last_name
    FROM tasks t
    JOIN users u ON t.created_by = u.id
    WHERE t.team_id = $1
)
SELECT id, team_id, title, description, status, fulfillment_status, review_status, created_by, due_date, created_at, first_name, last_name, COUNT(*) OVER() AS total_count
FROM base
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetTeamTasksParams struct {
	TeamID uuid.UUID `json:"team_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

type GetTeamTasksRow struct {
	ID                uuid.UUID                 `json:"id"`
	TeamID            uuid.UUID                 `json:"team_id"`
	Title             string                    `json:"title"`
	Description       sql.NullString            `json:"description"`
	Status            NullTaskStatus            `json:"status"`
	FulfillmentStatus NullTaskFulfillmentStatus `json:"fulfillment_status"`
	ReviewStatus      TaskReviewStatus          `json:"review_status"`
	CreatedBy         uuid.UUID                 `json:"created_by"`
	DueDate           sql.NullTime              `json:"due_date"`
	CreatedAt         sql.NullTime              `json:"created_at"`
	FirstName         sql.NullString            `json:"first_name"`
	LastName          sql.NullString            `json:"last_name"`
	TotalCount        int64                     `json:"total_count"`
}

func (q *Queries) GetTeamTasks(ctx context.Context, arg GetTeamTasksParams) ([]GetTeamTasksRow, error) {
	rows, err := q.db.QueryContext(ctx, getTeamTasks, arg.TeamID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTeamTasksRow
	for rows.Next() {
		var i GetTeamTasksRow
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.FulfillmentStatus,
			&i.ReviewStatus,
			&i.CreatedBy,
			&i.DueDate,
			&i.CreatedAt,
			&i.FirstName,
			&i.LastName,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUpdateComments = `-- name: GetUpdateComments :many
SELECT c.id, c.task_update_id, c.user_id, c.content, c.created_at,
       u.first_name, u.last_name
FROM task_update_comments c
LEFT JOIN users u ON c.user_id = u.id
WHERE c.task_update_id = $1
ORDER BY c.created_at ASC
LIMIT $2 OFFSET $3
`

type GetUpdateCommentsParams struct {
	TaskUpdateID uuid.UUID `json:"task_update_id"`
	Limit        int32     `json:"limit"`
	Offset       int32     `json:"offset"`
}

type GetUpdateCommentsRow struct {
	ID           uuid.UUID      `json:"id"`
	TaskUpdateID uuid.UUID      `json:"task_update_id"`
	UserID       uuid.NullUUID  `json:"user_id"`
	Content      string         `json:"content"`
	CreatedAt    sql.NullTime   `json:"created_at"`
	FirstName    sql.NullString `json:"first_name"`
	LastName     sql.NullString `json:"last_name"`
}

func (q *Queries) GetUpdateComments(ctx context.Context, arg GetUpdateCommentsParams) ([]GetUpdateCommentsRow, error) {
	rows, err := q.db.QueryContext(ctx, getUpdateComments, arg.TaskUpdateID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUpdateCommentsRow
	for rows.Next() {
		var i GetUpdateCommentsRow
		if err := rows.Scan(
			&i.ID,
			&i.TaskUpdateID,
			&i.UserID,
			&i.Content,
			&i.CreatedAt,
			&i.FirstName,
			&i.LastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertAttachment = `-- name: InsertAttachment :one
INSERT INTO attachments (
    task_id, task_update_id, task_comment_id, file_name, file_url, file_type, file_size_bytes, uploaded_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id
`

type InsertAttachmentParams struct {
	TaskID        uuid.NullUUID `json:"task_id"`
	TaskUpdateID  uuid.NullUUID `json:"task_update_id"`
	TaskCommentID uuid.NullUUID `json:"task_comment_id"`
	FileName      string        `json:"file_name"`
	FileUrl       string        `json:"file_url"`
	FileType      string        `json:"file_type"`
	FileSizeBytes sql.NullInt64 `json:"file_size_bytes"`
	UploadedBy    uuid.UUID     `json:"uploaded_by"`
}

func (q *Queries) InsertAttachment(ctx context.Context, arg InsertAttachmentParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, insertAttachment,
		arg.TaskID,
		arg.TaskUpdateID,
		arg.TaskCommentID,
		arg.FileName,
		arg.FileUrl,
		arg.FileType,
		arg.FileSizeBytes,
		arg.UploadedBy,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const isTaskAssignee = `-- name: IsTaskAssignee :one
SELECT EXISTS (
    SELECT 1 FROM task_participants
    WHERE task_id = $1 AND user_id = $2 AND role = 'ASSIGNEE'
)
`

type IsTaskAssigneeParams struct {
	TaskID uuid.UUID `json:"task_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) IsTaskAssignee(ctx context.Context, arg IsTaskAssigneeParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, isTaskAssignee, arg.TaskID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listTasksByTeam = `-- name: ListTasksByTeam :many
SELECT id, team_id, title, description, status, fulfillment_status, review_status, created_by, due_date, created_at FROM tasks
WHERE team_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListTasksByTeam(ctx context.Context, teamID uuid.UUID) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasksByTeam, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.FulfillmentStatus,
			&i.ReviewStatus,
			&i.CreatedBy,
			&i.DueDate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rejectTaskState = `-- name: RejectTaskState :exec
UPDATE tasks SET status = 'OPEN', fulfillment_status = 'PENDING', review_status = 'REJECTED', due_date = $2 WHERE id = $1
`

type RejectTaskStateParams struct {
	ID      uuid.UUID    `json:"id"`
	DueDate sql.NullTime `json:"due_date"`
}

func (q *Queries) RejectTaskState(ctx context.Context, arg RejectTaskStateParams) error {
	_, err := q.db.ExecContext(ctx, rejectTaskState, arg.ID, arg.DueDate)
	return err
}

const reopenTaskState = `-- name: ReopenTaskState :exec
UPDATE tasks SET status = 'OPEN', fulfillment_status = 'PENDING', review_status = 'UNSUBMITTED', due_date = $2 WHERE id = $1
`

type ReopenTaskStateParams struct {
	ID      uuid.UUID    `json:"id"`
	DueDate sql.NullTime `json:"due_date"`
}

func (q *Queries) ReopenTaskState(ctx context.Context, arg ReopenTaskStateParams) error {
	_, err := q.db.ExecContext(ctx, reopenTaskState, arg.ID, arg.DueDate)
	return err
}

const rescheduleReminder = `-- name: RescheduleReminder :exec
UPDATE reminders 
SET scheduled_at = $2 
WHERE id = $1
`

type RescheduleReminderParams struct {
	ID          uuid.UUID `json:"id"`
	ScheduledAt time.Time `json:"scheduled_at"`
}

func (q *Queries) RescheduleReminder(ctx context.Context, arg RescheduleReminderParams) error {
	_, err := q.db.ExecContext(ctx, rescheduleReminder, arg.ID, arg.ScheduledAt)
	return err
}

const submitTaskState = `-- name: SubmitTaskState :exec
UPDATE tasks SET fulfillment_status = 'COMPLETED', review_status = 'PENDING' WHERE id = $1
`

func (q *Queries) SubmitTaskState(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, submitTaskState, id)
	return err
}

const updateTaskDeadline = `-- name: UpdateTaskDeadline :exec
UPDATE tasks SET due_date = $2 WHERE id = $1
`

type UpdateTaskDeadlineParams struct {
	ID      uuid.UUID    `json:"id"`
	DueDate sql.NullTime `json:"due_date"`
}

func (q *Queries) UpdateTaskDeadline(ctx context.Context, arg UpdateTaskDeadlineParams) error {
	_, err := q.db.ExecContext(ctx, updateTaskDeadline, arg.ID, arg.DueDate)
	return err
}

const updateTaskDetails = `-- name: UpdateTaskDetails :exec
UPDATE tasks 
SET title = $1, 
    description = $2, 
    due_date = $3 
WHERE id = $4
`

type UpdateTaskDetailsParams struct {
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	DueDate     sql.NullTime   `json:"due_date"`
	ID          uuid.UUID      `json:"id"`
}

func (q *Queries) UpdateTaskDetails(ctx context.Context, arg UpdateTaskDetailsParams) error {
	_, err := q.db.ExecContext(ctx, updateTaskDetails,
		arg.Title,
		arg.Description,
		arg.DueDate,
		arg.ID,
	)
	return err
}

const updateTaskFulfillment = `-- name: UpdateTaskFulfillment :exec
UPDATE tasks 
SET fulfillment_status = $1 
WHERE id = $2
`

type UpdateTaskFulfillmentParams struct {
	FulfillmentStatus NullTaskFulfillmentStatus `json:"fulfillment_status"`
	ID                uuid.UUID                 `json:"id"`
}

func (q *Queries) UpdateTaskFulfillment(ctx context.Context, arg UpdateTaskFulfillmentParams) error {
	_, err := q.db.ExecContext(ctx, updateTaskFulfillment, arg.FulfillmentStatus, arg.ID)
	return err
}

const updateTaskStatus = `-- name: UpdateTaskStatus :exec
UPDATE tasks 
SET status = $1 
WHERE id = $2
`

type UpdateTaskStatusParams struct {
	Status NullTaskStatus `json:"status"`
	ID     uuid.UUID      `json:"id"`
}

func (q *Queries) UpdateTaskStatus(ctx context.Context, arg UpdateTaskStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateTaskStatus, arg.Status, arg.ID)
	return err
}
