// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: task.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	_ "github.com/lib/pq"
)

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (
    team_id, title, description, status, fulfillment_status, created_by, due_date
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, team_id, title, description, status, fulfillment_status, created_by, due_date, created_at
`

type CreateTaskParams struct {
	TeamID            uuid.UUID                 `json:"team_id"`
	Title             string                    `json:"title"`
	Description       sql.NullString            `json:"description"`
	Status            NullTaskStatus            `json:"status"`
	FulfillmentStatus NullTaskFulfillmentStatus `json:"fulfillment_status"`
	CreatedBy         uuid.UUID                 `json:"created_by"`
	DueDate           sql.NullTime              `json:"due_date"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, createTask,
		arg.TeamID,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.FulfillmentStatus,
		arg.CreatedBy,
		arg.DueDate,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.FulfillmentStatus,
		&i.CreatedBy,
		&i.DueDate,
		&i.CreatedAt,
	)
	return i, err
}

const getTaskByID = `-- name: GetTaskByID :one
SELECT id, team_id, title, description, status, fulfillment_status, created_by, due_date, created_at FROM tasks
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTaskByID(ctx context.Context, id uuid.UUID) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTaskByID, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.FulfillmentStatus,
		&i.CreatedBy,
		&i.DueDate,
		&i.CreatedAt,
	)
	return i, err
}

const listTasksByTeam = `-- name: ListTasksByTeam :many
SELECT id, team_id, title, description, status, fulfillment_status, created_by, due_date, created_at FROM tasks
WHERE team_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListTasksByTeam(ctx context.Context, teamID uuid.UUID) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasksByTeam, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.FulfillmentStatus,
			&i.CreatedBy,
			&i.DueDate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
