// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: team.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const checkTeamAdminStatus = `-- name: CheckTeamAdminStatus :one
SELECT EXISTS (
    SELECT 1 FROM team_members 
    WHERE team_id = $1 AND user_id = $2 AND team_role = 'TEAM_ADMIN'
)
`

type CheckTeamAdminStatusParams struct {
	TeamID uuid.UUID `json:"team_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) CheckTeamAdminStatus(ctx context.Context, arg CheckTeamAdminStatusParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkTeamAdminStatus, arg.TeamID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createTeam = `-- name: CreateTeam :one
INSERT INTO teams (org_id, name) VALUES ($1, $2) RETURNING id
`

type CreateTeamParams struct {
	OrgID uuid.UUID `json:"org_id"`
	Name  string    `json:"name"`
}

func (q *Queries) CreateTeam(ctx context.Context, arg CreateTeamParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, createTeam, arg.OrgID, arg.Name)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getAdminManagedTeams = `-- name: GetAdminManagedTeams :many
SELECT t.id, t.name 
FROM teams t
JOIN team_members tm ON t.id = tm.team_id
WHERE tm.user_id = $1 AND tm.team_role = 'TEAM_ADMIN'
ORDER BY t.name ASC
`

type GetAdminManagedTeamsRow struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

func (q *Queries) GetAdminManagedTeams(ctx context.Context, userID uuid.UUID) ([]GetAdminManagedTeamsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAdminManagedTeams, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAdminManagedTeamsRow
	for rows.Next() {
		var i GetAdminManagedTeamsRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAdminTeamNames = `-- name: GetAdminTeamNames :many
SELECT t.name 
FROM teams t
JOIN team_members tm ON t.id = tm.team_id
WHERE tm.user_id = $1 AND tm.team_role = 'TEAM_ADMIN'
ORDER BY t.name
`

func (q *Queries) GetAdminTeamNames(ctx context.Context, userID uuid.UUID) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getAdminTeamNames, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEmployeeTeams = `-- name: GetEmployeeTeams :many
SELECT 
    t.id, 
    t.name, 
    tm.team_role,
    (SELECT COUNT(user_id) FROM team_members WHERE team_id = t.id) AS member_count
FROM teams t
JOIN team_members tm ON t.id = tm.team_id
WHERE tm.user_id = $1
ORDER BY t.name ASC
`

type GetEmployeeTeamsRow struct {
	ID          uuid.UUID    `json:"id"`
	Name        string       `json:"name"`
	TeamRole    TeamRoleEnum `json:"team_role"`
	MemberCount int64        `json:"member_count"`
}

func (q *Queries) GetEmployeeTeams(ctx context.Context, userID uuid.UUID) ([]GetEmployeeTeamsRow, error) {
	rows, err := q.db.QueryContext(ctx, getEmployeeTeams, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEmployeeTeamsRow
	for rows.Next() {
		var i GetEmployeeTeamsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TeamRole,
			&i.MemberCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrgTeams = `-- name: GetOrgTeams :many
SELECT t.id, t.name, COUNT(tm.user_id) AS member_count
FROM teams t
LEFT JOIN team_members tm ON t.id = tm.team_id
WHERE t.org_id = $1
GROUP BY t.id
ORDER BY t.name ASC
`

type GetOrgTeamsRow struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	MemberCount int64     `json:"member_count"`
}

func (q *Queries) GetOrgTeams(ctx context.Context, orgID uuid.UUID) ([]GetOrgTeamsRow, error) {
	rows, err := q.db.QueryContext(ctx, getOrgTeams, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOrgTeamsRow
	for rows.Next() {
		var i GetOrgTeamsRow
		if err := rows.Scan(&i.ID, &i.Name, &i.MemberCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTeamAdminCount = `-- name: GetTeamAdminCount :one
SELECT COUNT(*) FROM team_members 
WHERE team_id = $1 AND team_role = 'TEAM_ADMIN'
`

func (q *Queries) GetTeamAdminCount(ctx context.Context, teamID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, getTeamAdminCount, teamID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getTeamAdminsByTask = `-- name: GetTeamAdminsByTask :many
SELECT tm.user_id 
FROM team_members tm
JOIN tasks t ON tm.team_id = t.team_id
WHERE t.id = $1 AND tm.team_role = 'TEAM_ADMIN'
`

func (q *Queries) GetTeamAdminsByTask(ctx context.Context, id uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, getTeamAdminsByTask, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var user_id uuid.UUID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTeamEmployeesPaginated = `-- name: GetTeamEmployeesPaginated :many
SELECT 
    u.id, u.first_name, u.last_name, u.email_id, u.status,
    t.name as team_name, tm_target.team_role::text as team_role,
    COUNT(*) OVER() AS total_count
FROM team_members tm_admin
JOIN teams t ON tm_admin.team_id = t.id
JOIN team_members tm_target ON t.id = tm_target.team_id
JOIN users u ON tm_target.user_id = u.id
WHERE tm_admin.user_id = $1 
  AND tm_admin.team_role = 'TEAM_ADMIN'
  AND ($4::text = '' OR u.email_id ILIKE '%' || $4 || '%' OR u.first_name ILIKE '%' || $4 || '%' OR u.last_name ILIKE '%' || $4 || '%')
  AND ($5::text = '' OR t.name = $5)
  AND ($6::text = '' OR tm_target.team_role::text = $6)
  AND ($7::text = '' OR u.status::text = $7)
ORDER BY t.name ASC, u.created_at DESC
LIMIT $2 OFFSET $3
`

type GetTeamEmployeesPaginatedParams struct {
	UserID       uuid.UUID `json:"user_id"`
	Limit        int32     `json:"limit"`
	Offset       int32     `json:"offset"`
	SearchTerm   string    `json:"search_term"`
	TeamFilter   string    `json:"team_filter"`
	RoleFilter   string    `json:"role_filter"`
	StatusFilter string    `json:"status_filter"`
}

type GetTeamEmployeesPaginatedRow struct {
	ID         uuid.UUID      `json:"id"`
	FirstName  sql.NullString `json:"first_name"`
	LastName   sql.NullString `json:"last_name"`
	EmailID    string         `json:"email_id"`
	Status     NullUserStatus `json:"status"`
	TeamName   string         `json:"team_name"`
	TeamRole   string         `json:"team_role"`
	TotalCount int64          `json:"total_count"`
}

func (q *Queries) GetTeamEmployeesPaginated(ctx context.Context, arg GetTeamEmployeesPaginatedParams) ([]GetTeamEmployeesPaginatedRow, error) {
	rows, err := q.db.QueryContext(ctx, getTeamEmployeesPaginated,
		arg.UserID,
		arg.Limit,
		arg.Offset,
		arg.SearchTerm,
		arg.TeamFilter,
		arg.RoleFilter,
		arg.StatusFilter,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTeamEmployeesPaginatedRow
	for rows.Next() {
		var i GetTeamEmployeesPaginatedRow
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.EmailID,
			&i.Status,
			&i.TeamName,
			&i.TeamRole,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTeamMembersDetails = `-- name: GetTeamMembersDetails :many
SELECT u.id, u.first_name, u.last_name, u.email_id, tm.team_role::text
FROM team_members tm
JOIN users u ON tm.user_id = u.id
WHERE tm.team_id = $1
ORDER BY tm.team_role DESC, u.first_name ASC
`

type GetTeamMembersDetailsRow struct {
	ID         uuid.UUID      `json:"id"`
	FirstName  sql.NullString `json:"first_name"`
	LastName   sql.NullString `json:"last_name"`
	EmailID    string         `json:"email_id"`
	TmTeamRole string         `json:"tm_team_role"`
}

func (q *Queries) GetTeamMembersDetails(ctx context.Context, teamID uuid.UUID) ([]GetTeamMembersDetailsRow, error) {
	rows, err := q.db.QueryContext(ctx, getTeamMembersDetails, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTeamMembersDetailsRow
	for rows.Next() {
		var i GetTeamMembersDetailsRow
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.EmailID,
			&i.TmTeamRole,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTotalUsersInAdminTeams = `-- name: GetTotalUsersInAdminTeams :one
SELECT COUNT(DISTINCT tm2.user_id)
FROM team_members tm1
JOIN team_members tm2 ON tm1.team_id = tm2.team_id
WHERE tm1.user_id = $1 AND tm1.team_role = 'TEAM_ADMIN'
`

func (q *Queries) GetTotalUsersInAdminTeams(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, getTotalUsersInAdminTeams, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getUserTeams = `-- name: GetUserTeams :many
SELECT t.id, t.name, tm.team_role::text
FROM team_members tm
JOIN teams t ON tm.team_id = t.id
WHERE tm.user_id = $1
ORDER BY t.name ASC
`

type GetUserTeamsRow struct {
	ID         uuid.UUID `json:"id"`
	Name       string    `json:"name"`
	TmTeamRole string    `json:"tm_team_role"`
}

func (q *Queries) GetUserTeams(ctx context.Context, userID uuid.UUID) ([]GetUserTeamsRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserTeams, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserTeamsRow
	for rows.Next() {
		var i GetUserTeamsRow
		if err := rows.Scan(&i.ID, &i.Name, &i.TmTeamRole); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeTeamMember = `-- name: RemoveTeamMember :exec
DELETE FROM team_members WHERE team_id = $1 AND user_id = $2
`

type RemoveTeamMemberParams struct {
	TeamID uuid.UUID `json:"team_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) RemoveTeamMember(ctx context.Context, arg RemoveTeamMemberParams) error {
	_, err := q.db.ExecContext(ctx, removeTeamMember, arg.TeamID, arg.UserID)
	return err
}

const upsertTeamMember = `-- name: UpsertTeamMember :exec
INSERT INTO team_members (team_id, user_id, team_role) 
VALUES ($1, $2, $3)
ON CONFLICT (team_id, user_id) 
DO UPDATE SET team_role = EXCLUDED.team_role
`

type UpsertTeamMemberParams struct {
	TeamID   uuid.UUID    `json:"team_id"`
	UserID   uuid.UUID    `json:"user_id"`
	TeamRole TeamRoleEnum `json:"team_role"`
}

func (q *Queries) UpsertTeamMember(ctx context.Context, arg UpsertTeamMemberParams) error {
	_, err := q.db.ExecContext(ctx, upsertTeamMember, arg.TeamID, arg.UserID, arg.TeamRole)
	return err
}
