// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: team.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getTotalUsersInAdminTeams = `-- name: GetTotalUsersInAdminTeams :one
SELECT COUNT(DISTINCT tm2.user_id)
FROM team_members tm1
JOIN team_members tm2 ON tm1.team_id = tm2.team_id
WHERE tm1.user_id = $1 AND tm1.team_role = 'TEAM_ADMIN'
`

func (q *Queries) GetTotalUsersInAdminTeams(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, getTotalUsersInAdminTeams, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}
