// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transcriptions.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const completeTranscription = `-- name: CompleteTranscription :exec
UPDATE transcriptions SET status = 'COMPLETED', transcript_text = $2, updated_at = NOW() WHERE id = $1
`

type CompleteTranscriptionParams struct {
	ID             uuid.UUID      `json:"id"`
	TranscriptText sql.NullString `json:"transcript_text"`
}

func (q *Queries) CompleteTranscription(ctx context.Context, arg CompleteTranscriptionParams) error {
	_, err := q.db.ExecContext(ctx, completeTranscription, arg.ID, arg.TranscriptText)
	return err
}

const failTranscription = `-- name: FailTranscription :exec
UPDATE transcriptions SET status = 'FAILED', error_message = $2, updated_at = NOW() WHERE id = $1
`

type FailTranscriptionParams struct {
	ID           uuid.UUID      `json:"id"`
	ErrorMessage sql.NullString `json:"error_message"`
}

func (q *Queries) FailTranscription(ctx context.Context, arg FailTranscriptionParams) error {
	_, err := q.db.ExecContext(ctx, failTranscription, arg.ID, arg.ErrorMessage)
	return err
}

const getPendingTranscriptions = `-- name: GetPendingTranscriptions :many
SELECT t.id, t.attachment_id, a.file_url
FROM transcriptions t
JOIN attachments a ON t.attachment_id = a.id
WHERE t.status = 'PENDING'
LIMIT 10
FOR UPDATE OF t SKIP LOCKED
`

type GetPendingTranscriptionsRow struct {
	ID           uuid.UUID `json:"id"`
	AttachmentID uuid.UUID `json:"attachment_id"`
	FileUrl      string    `json:"file_url"`
}

func (q *Queries) GetPendingTranscriptions(ctx context.Context) ([]GetPendingTranscriptionsRow, error) {
	rows, err := q.db.QueryContext(ctx, getPendingTranscriptions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPendingTranscriptionsRow
	for rows.Next() {
		var i GetPendingTranscriptionsRow
		if err := rows.Scan(&i.ID, &i.AttachmentID, &i.FileUrl); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTranscriptionByAttachmentID = `-- name: GetTranscriptionByAttachmentID :one
SELECT id, status, transcript_text, error_message
FROM transcriptions
WHERE attachment_id = $1
`

type GetTranscriptionByAttachmentIDRow struct {
	ID             uuid.UUID               `json:"id"`
	Status         NullTranscriptionStatus `json:"status"`
	TranscriptText sql.NullString          `json:"transcript_text"`
	ErrorMessage   sql.NullString          `json:"error_message"`
}

func (q *Queries) GetTranscriptionByAttachmentID(ctx context.Context, attachmentID uuid.UUID) (GetTranscriptionByAttachmentIDRow, error) {
	row := q.db.QueryRowContext(ctx, getTranscriptionByAttachmentID, attachmentID)
	var i GetTranscriptionByAttachmentIDRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.TranscriptText,
		&i.ErrorMessage,
	)
	return i, err
}

const getTranscriptionsByAttachmentIDs = `-- name: GetTranscriptionsByAttachmentIDs :many
SELECT attachment_id, status, transcript_text
FROM transcriptions
WHERE attachment_id = ANY($1::uuid[])
`

type GetTranscriptionsByAttachmentIDsRow struct {
	AttachmentID   uuid.UUID               `json:"attachment_id"`
	Status         NullTranscriptionStatus `json:"status"`
	TranscriptText sql.NullString          `json:"transcript_text"`
}

func (q *Queries) GetTranscriptionsByAttachmentIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]GetTranscriptionsByAttachmentIDsRow, error) {
	rows, err := q.db.QueryContext(ctx, getTranscriptionsByAttachmentIDs, pq.Array(dollar_1))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTranscriptionsByAttachmentIDsRow
	for rows.Next() {
		var i GetTranscriptionsByAttachmentIDsRow
		if err := rows.Scan(&i.AttachmentID, &i.Status, &i.TranscriptText); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertTranscription = `-- name: InsertTranscription :exec
INSERT INTO transcriptions (attachment_id) VALUES ($1) ON CONFLICT (attachment_id) DO NOTHING
`

func (q *Queries) InsertTranscription(ctx context.Context, attachmentID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, insertTranscription, attachmentID)
	return err
}

const setTranscriptionProcessing = `-- name: SetTranscriptionProcessing :exec
UPDATE transcriptions SET status = 'PROCESSING', updated_at = NOW() WHERE id = $1
`

func (q *Queries) SetTranscriptionProcessing(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, setTranscriptionProcessing, id)
	return err
}
