// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const addUserSystemRole = `-- name: AddUserSystemRole :one
INSERT INTO user_system_roles (
    user_id, org_id, role
) VALUES (
    $1, $2, $3
) RETURNING user_id, org_id, role, granted_at
`

type AddUserSystemRoleParams struct {
	UserID uuid.UUID  `json:"user_id"`
	OrgID  uuid.UUID  `json:"org_id"`
	Role   SystemRole `json:"role"`
}

// Assigns a system role to a user, scoped to one org.
func (q *Queries) AddUserSystemRole(ctx context.Context, arg AddUserSystemRoleParams) (UserSystemRole, error) {
	row := q.db.QueryRowContext(ctx, addUserSystemRole, arg.UserID, arg.OrgID, arg.Role)
	var i UserSystemRole
	err := row.Scan(
		&i.UserID,
		&i.OrgID,
		&i.Role,
		&i.GrantedAt,
	)
	return i, err
}

const createInvitedUser = `-- name: CreateInvitedUser :one
INSERT INTO users (
    email_id
) VALUES (
    $1
)
RETURNING id, org_id, status, first_name, last_name, email_id, face_s3_uri, phone_number, created_at
`

// Shared identity only; the org_memberships row (status INVITED) is created
// separately by the caller in the same transaction.
func (q *Queries) CreateInvitedUser(ctx context.Context, emailID string) (User, error) {
	row := q.db.QueryRowContext(ctx, createInvitedUser, emailID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Status,
		&i.FirstName,
		&i.LastName,
		&i.EmailID,
		&i.FaceS3Uri,
		&i.PhoneNumber,
		&i.CreatedAt,
	)
	return i, err
}

const createOrgMembership = `-- name: CreateOrgMembership :one
INSERT INTO org_memberships (user_id, org_id, status)
VALUES ($1, $2, $3)
RETURNING id, user_id, org_id, status, created_at
`

type CreateOrgMembershipParams struct {
	UserID uuid.UUID  `json:"user_id"`
	OrgID  uuid.UUID  `json:"org_id"`
	Status UserStatus `json:"status"`
}

func (q *Queries) CreateOrgMembership(ctx context.Context, arg CreateOrgMembershipParams) (OrgMembership, error) {
	row := q.db.QueryRowContext(ctx, createOrgMembership, arg.UserID, arg.OrgID, arg.Status)
	var i OrgMembership
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OrgID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT into users (
    first_name, last_name, email_id, phone_number, face_s3_uri
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, org_id, status, first_name, last_name, email_id, face_s3_uri, phone_number, created_at
`

type CreateUserParams struct {
	FirstName   sql.NullString `json:"first_name"`
	LastName    sql.NullString `json:"last_name"`
	EmailID     string         `json:"email_id"`
	PhoneNumber sql.NullString `json:"phone_number"`
	FaceS3Uri   sql.NullString `json:"face_s3_uri"`
}

// Shared identity only — org_id/status live on org_memberships, written
// separately by the caller in the same transaction (multi-org membership).
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.FirstName,
		arg.LastName,
		arg.EmailID,
		arg.PhoneNumber,
		arg.FaceS3Uri,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Status,
		&i.FirstName,
		&i.LastName,
		&i.EmailID,
		&i.FaceS3Uri,
		&i.PhoneNumber,
		&i.CreatedAt,
	)
	return i, err
}

const createUserCredentials = `-- name: CreateUserCredentials :one
INSERT into user_credentials (
    user_id, password_hash
) VALUES (
    $1, $2
)
RETURNING user_id, password_hash, updated_at
`

type CreateUserCredentialsParams struct {
	UserID       uuid.UUID `json:"user_id"`
	PasswordHash string    `json:"password_hash"`
}

func (q *Queries) CreateUserCredentials(ctx context.Context, arg CreateUserCredentialsParams) (UserCredential, error) {
	row := q.db.QueryRowContext(ctx, createUserCredentials, arg.UserID, arg.PasswordHash)
	var i UserCredential
	err := row.Scan(&i.UserID, &i.PasswordHash, &i.UpdatedAt)
	return i, err
}

const deleteUserSystemRoles = `-- name: DeleteUserSystemRoles :exec
DELETE FROM user_system_roles WHERE user_id = $1 AND org_id = $2
`

type DeleteUserSystemRolesParams struct {
	UserID uuid.UUID `json:"user_id"`
	OrgID  uuid.UUID `json:"org_id"`
}

// Scoped to one org — must never wipe a person's roles in a different org
// they also belong to.
func (q *Queries) DeleteUserSystemRoles(ctx context.Context, arg DeleteUserSystemRolesParams) error {
	_, err := q.db.ExecContext(ctx, deleteUserSystemRoles, arg.UserID, arg.OrgID)
	return err
}

const getAssignedOrgUsers = `-- name: GetAssignedOrgUsers :many
WITH base AS (
    SELECT u.id, u.first_name, u.last_name, u.email_id, om.status, u.created_at
    FROM users u
    JOIN org_memberships om ON om.user_id = u.id
    WHERE om.org_id = $1
      AND EXISTS (
        SELECT 1 FROM team_members tm
        JOIN teams t ON t.id = tm.team_id
        WHERE tm.user_id = u.id AND t.org_id = $1
      )
)
SELECT id, first_name, last_name, email_id, status, created_at, COUNT(*) OVER() AS total_count
FROM base
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetAssignedOrgUsersParams struct {
	OrgID  uuid.UUID `json:"org_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

type GetAssignedOrgUsersRow struct {
	ID         uuid.UUID      `json:"id"`
	FirstName  sql.NullString `json:"first_name"`
	LastName   sql.NullString `json:"last_name"`
	EmailID    string         `json:"email_id"`
	Status     UserStatus     `json:"status"`
	CreatedAt  sql.NullTime   `json:"created_at"`
	TotalCount int64          `json:"total_count"`
}

func (q *Queries) GetAssignedOrgUsers(ctx context.Context, arg GetAssignedOrgUsersParams) ([]GetAssignedOrgUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, getAssignedOrgUsers, arg.OrgID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAssignedOrgUsersRow
	for rows.Next() {
		var i GetAssignedOrgUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.EmailID,
			&i.Status,
			&i.CreatedAt,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEmailByUser = `-- name: GetEmailByUser :one
SELECT email_id from users where id = $1 LIMIT 1
`

func (q *Queries) GetEmailByUser(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRowContext(ctx, getEmailByUser, id)
	var email_id string
	err := row.Scan(&email_id)
	return email_id, err
}

const getFullUserProfile = `-- name: GetFullUserProfile :one
SELECT
    u.id, u.first_name, u.last_name, u.email_id, u.phone_number, om.status, u.face_s3_uri,
    o.name as org_name
FROM users u
JOIN org_memberships om ON om.user_id = u.id
JOIN organizations o ON o.id = om.org_id
WHERE u.id = $1 AND om.org_id = $2 LIMIT 1
`

type GetFullUserProfileParams struct {
	ID    uuid.UUID `json:"id"`
	OrgID uuid.UUID `json:"org_id"`
}

type GetFullUserProfileRow struct {
	ID          uuid.UUID      `json:"id"`
	FirstName   sql.NullString `json:"first_name"`
	LastName    sql.NullString `json:"last_name"`
	EmailID     string         `json:"email_id"`
	PhoneNumber sql.NullString `json:"phone_number"`
	Status      UserStatus     `json:"status"`
	FaceS3Uri   sql.NullString `json:"face_s3_uri"`
	OrgName     string         `json:"org_name"`
}

func (q *Queries) GetFullUserProfile(ctx context.Context, arg GetFullUserProfileParams) (GetFullUserProfileRow, error) {
	row := q.db.QueryRowContext(ctx, getFullUserProfile, arg.ID, arg.OrgID)
	var i GetFullUserProfileRow
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.EmailID,
		&i.PhoneNumber,
		&i.Status,
		&i.FaceS3Uri,
		&i.OrgName,
	)
	return i, err
}

const getMembershipStatus = `-- name: GetMembershipStatus :one
SELECT status FROM org_memberships WHERE user_id = $1 AND org_id = $2
`

type GetMembershipStatusParams struct {
	UserID uuid.UUID `json:"user_id"`
	OrgID  uuid.UUID `json:"org_id"`
}

func (q *Queries) GetMembershipStatus(ctx context.Context, arg GetMembershipStatusParams) (UserStatus, error) {
	row := q.db.QueryRowContext(ctx, getMembershipStatus, arg.UserID, arg.OrgID)
	var status UserStatus
	err := row.Scan(&status)
	return status, err
}

const getPendingInvitedUser = `-- name: GetPendingInvitedUser :one
SELECT u.id, u.email_id, om.org_id, om.status, usr.role
FROM users u
JOIN org_memberships om ON om.user_id = u.id
JOIN user_system_roles usr ON u.id = usr.user_id AND usr.org_id = om.org_id
WHERE u.email_id = $1 AND om.org_id = $2
`

type GetPendingInvitedUserParams struct {
	EmailID string    `json:"email_id"`
	OrgID   uuid.UUID `json:"org_id"`
}

type GetPendingInvitedUserRow struct {
	ID      uuid.UUID  `json:"id"`
	EmailID string     `json:"email_id"`
	OrgID   uuid.UUID  `json:"org_id"`
	Status  UserStatus `json:"status"`
	Role    SystemRole `json:"role"`
}

func (q *Queries) GetPendingInvitedUser(ctx context.Context, arg GetPendingInvitedUserParams) (GetPendingInvitedUserRow, error) {
	row := q.db.QueryRowContext(ctx, getPendingInvitedUser, arg.EmailID, arg.OrgID)
	var i GetPendingInvitedUserRow
	err := row.Scan(
		&i.ID,
		&i.EmailID,
		&i.OrgID,
		&i.Status,
		&i.Role,
	)
	return i, err
}

const getTotalUsersByOrg = `-- name: GetTotalUsersByOrg :one
SELECT COUNT(*) FROM org_memberships
WHERE org_id = $1
`

func (q *Queries) GetTotalUsersByOrg(ctx context.Context, orgID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, getTotalUsersByOrg, orgID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getUnassignedOrgUsers = `-- name: GetUnassignedOrgUsers :many
WITH base AS (
    SELECT u.id, u.first_name, u.last_name, u.email_id, om.status, u.created_at
    FROM users u
    JOIN org_memberships om ON om.user_id = u.id
    WHERE om.org_id = $1
      AND NOT EXISTS (
        SELECT 1 FROM team_members tm
        JOIN teams t ON t.id = tm.team_id
        WHERE tm.user_id = u.id AND t.org_id = $1
      )
)
SELECT id, first_name, last_name, email_id, status, created_at, COUNT(*) OVER() AS total_count
FROM base
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetUnassignedOrgUsersParams struct {
	OrgID  uuid.UUID `json:"org_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

type GetUnassignedOrgUsersRow struct {
	ID         uuid.UUID      `json:"id"`
	FirstName  sql.NullString `json:"first_name"`
	LastName   sql.NullString `json:"last_name"`
	EmailID    string         `json:"email_id"`
	Status     UserStatus     `json:"status"`
	CreatedAt  sql.NullTime   `json:"created_at"`
	TotalCount int64          `json:"total_count"`
}

func (q *Queries) GetUnassignedOrgUsers(ctx context.Context, arg GetUnassignedOrgUsersParams) ([]GetUnassignedOrgUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, getUnassignedOrgUsers, arg.OrgID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUnassignedOrgUsersRow
	for rows.Next() {
		var i GetUnassignedOrgUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.EmailID,
			&i.Status,
			&i.CreatedAt,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, org_id, status, first_name, last_name, email_id, face_s3_uri, phone_number, created_at FROM users 
WHERE email_id = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, emailID string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, emailID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Status,
		&i.FirstName,
		&i.LastName,
		&i.EmailID,
		&i.FaceS3Uri,
		&i.PhoneNumber,
		&i.CreatedAt,
	)
	return i, err
}

const getUserCredentials = `-- name: GetUserCredentials :one
SELECT user_id, password_hash, updated_at FROM user_credentials 
WHERE user_id = $1 LIMIT 1
`

func (q *Queries) GetUserCredentials(ctx context.Context, userID uuid.UUID) (UserCredential, error) {
	row := q.db.QueryRowContext(ctx, getUserCredentials, userID)
	var i UserCredential
	err := row.Scan(&i.UserID, &i.PasswordHash, &i.UpdatedAt)
	return i, err
}

const getUserFaceURI = `-- name: GetUserFaceURI :one
SELECT face_s3_uri FROM users WHERE id = $1
`

func (q *Queries) GetUserFaceURI(ctx context.Context, id uuid.UUID) (sql.NullString, error) {
	row := q.db.QueryRowContext(ctx, getUserFaceURI, id)
	var face_s3_uri sql.NullString
	err := row.Scan(&face_s3_uri)
	return face_s3_uri, err
}

const getUserNameByID = `-- name: GetUserNameByID :one
SELECT first_name, last_name FROM users WHERE id = $1
`

type GetUserNameByIDRow struct {
	FirstName sql.NullString `json:"first_name"`
	LastName  sql.NullString `json:"last_name"`
}

func (q *Queries) GetUserNameByID(ctx context.Context, id uuid.UUID) (GetUserNameByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getUserNameByID, id)
	var i GetUserNameByIDRow
	err := row.Scan(&i.FirstName, &i.LastName)
	return i, err
}

const getUserOrgMemberships = `-- name: GetUserOrgMemberships :many
SELECT
    om.org_id,
    o.name AS org_name,
    om.status,
    COALESCE(
        (SELECT array_agg(role)::text[] FROM user_system_roles WHERE user_id = om.user_id AND org_id = om.org_id),
    '{}') AS roles
FROM org_memberships om
JOIN organizations o ON o.id = om.org_id
WHERE om.user_id = $1 AND om.status = 'ACTIVE'
ORDER BY o.name
`

type GetUserOrgMembershipsRow struct {
	OrgID   uuid.UUID   `json:"org_id"`
	OrgName string      `json:"org_name"`
	Status  UserStatus  `json:"status"`
	Roles   interface{} `json:"roles"`
}

// Every active org a person belongs to, with the role(s) they hold in each —
// powers the login org-picker and the org-switcher menu. One row per org
// (roles aggregated) since a person can hold more than one role per org.
func (q *Queries) GetUserOrgMemberships(ctx context.Context, userID uuid.UUID) ([]GetUserOrgMembershipsRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserOrgMemberships, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserOrgMembershipsRow
	for rows.Next() {
		var i GetUserOrgMembershipsRow
		if err := rows.Scan(
			&i.OrgID,
			&i.OrgName,
			&i.Status,
			&i.Roles,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserSystemRoles = `-- name: GetUserSystemRoles :many
SELECT role FROM user_system_roles
WHERE user_id = $1 AND org_id = $2
`

type GetUserSystemRolesParams struct {
	UserID uuid.UUID `json:"user_id"`
	OrgID  uuid.UUID `json:"org_id"`
}

// Fetches the roles a user holds in one specific org (not global — a person
// can hold different roles in different orgs).
func (q *Queries) GetUserSystemRoles(ctx context.Context, arg GetUserSystemRolesParams) ([]SystemRole, error) {
	rows, err := q.db.QueryContext(ctx, getUserSystemRoles, arg.UserID, arg.OrgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SystemRole
	for rows.Next() {
		var role SystemRole
		if err := rows.Scan(&role); err != nil {
			return nil, err
		}
		items = append(items, role)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserTeamsWithAdmins = `-- name: GetUserTeamsWithAdmins :many
SELECT 
    t.name as team_name,
    tm.team_role as user_team_role,
    COALESCE(
        (SELECT array_agg(u2.email_id)::text[]
         FROM team_members tm2
         JOIN users u2 ON tm2.user_id = u2.id
         WHERE tm2.team_id = t.id AND tm2.team_role = 'TEAM_ADMIN'
        ), '{}'
    ) as team_admin_emails
FROM team_members tm
JOIN teams t ON tm.team_id = t.id
WHERE tm.user_id = $1 AND t.org_id = $2
`

type GetUserTeamsWithAdminsParams struct {
	UserID uuid.UUID `json:"user_id"`
	OrgID  uuid.UUID `json:"org_id"`
}

type GetUserTeamsWithAdminsRow struct {
	TeamName        string       `json:"team_name"`
	UserTeamRole    TeamRoleEnum `json:"user_team_role"`
	TeamAdminEmails interface{}  `json:"team_admin_emails"`
}

func (q *Queries) GetUserTeamsWithAdmins(ctx context.Context, arg GetUserTeamsWithAdminsParams) ([]GetUserTeamsWithAdminsRow, error) {
	rows, err := q.db.QueryContext(ctx, getUserTeamsWithAdmins, arg.UserID, arg.OrgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserTeamsWithAdminsRow
	for rows.Next() {
		var i GetUserTeamsWithAdminsRow
		if err := rows.Scan(&i.TeamName, &i.UserTeamRole, &i.TeamAdminEmails); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsersByOrg = `-- name: GetUsersByOrg :many
SELECT
    u.id, u.first_name, u.last_name, u.email_id, om.status,
    COALESCE(
        (SELECT array_agg(role)::text[]
         FROM user_system_roles
         WHERE user_id = u.id AND org_id = om.org_id),
    '{}') AS roles
FROM users u
JOIN org_memberships om ON om.user_id = u.id
WHERE om.org_id = $1
ORDER BY u.created_at DESC
`

type GetUsersByOrgRow struct {
	ID        uuid.UUID      `json:"id"`
	FirstName sql.NullString `json:"first_name"`
	LastName  sql.NullString `json:"last_name"`
	EmailID   string         `json:"email_id"`
	Status    UserStatus     `json:"status"`
	Roles     interface{}    `json:"roles"`
}

func (q *Queries) GetUsersByOrg(ctx context.Context, orgID uuid.UUID) ([]GetUsersByOrgRow, error) {
	rows, err := q.db.QueryContext(ctx, getUsersByOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUsersByOrgRow
	for rows.Next() {
		var i GetUsersByOrgRow
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.EmailID,
			&i.Status,
			&i.Roles,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsersByOrgPaginated = `-- name: GetUsersByOrgPaginated :many
SELECT
    u.id, u.first_name, u.last_name, u.email_id, om.status,
    COALESCE(
        (SELECT array_agg(role)::text[]
         FROM user_system_roles
         WHERE user_id = u.id AND org_id = om.org_id),
    '{}') AS roles,
    COUNT(*) OVER() AS total_count
FROM users u
JOIN org_memberships om ON om.user_id = u.id
WHERE om.org_id = $1
  AND ($4::text = '' OR u.email_id ILIKE '%' || $4 || '%' OR u.first_name ILIKE '%' || $4 || '%' OR u.last_name ILIKE '%' || $4 || '%')
  AND ($5::text = '' OR om.status::text = $5)
  AND ($6::text = '' OR EXISTS (
        SELECT 1 FROM user_system_roles WHERE user_id = u.id AND org_id = om.org_id AND role::text = $6
      ))
ORDER BY u.created_at DESC
LIMIT $2 OFFSET $3
`

type GetUsersByOrgPaginatedParams struct {
	OrgID        uuid.UUID `json:"org_id"`
	Limit        int32     `json:"limit"`
	Offset       int32     `json:"offset"`
	SearchTerm   string    `json:"search_term"`
	StatusFilter string    `json:"status_filter"`
	RoleFilter   string    `json:"role_filter"`
}

type GetUsersByOrgPaginatedRow struct {
	ID         uuid.UUID      `json:"id"`
	FirstName  sql.NullString `json:"first_name"`
	LastName   sql.NullString `json:"last_name"`
	EmailID    string         `json:"email_id"`
	Status     UserStatus     `json:"status"`
	Roles      interface{}    `json:"roles"`
	TotalCount int64          `json:"total_count"`
}

func (q *Queries) GetUsersByOrgPaginated(ctx context.Context, arg GetUsersByOrgPaginatedParams) ([]GetUsersByOrgPaginatedRow, error) {
	rows, err := q.db.QueryContext(ctx, getUsersByOrgPaginated,
		arg.OrgID,
		arg.Limit,
		arg.Offset,
		arg.SearchTerm,
		arg.StatusFilter,
		arg.RoleFilter,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUsersByOrgPaginatedRow
	for rows.Next() {
		var i GetUsersByOrgPaginatedRow
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.EmailID,
			&i.Status,
			&i.Roles,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertUserSystemRole = `-- name: InsertUserSystemRole :exec
INSERT INTO user_system_roles (user_id, org_id, role) VALUES ($1, $2, $3)
`

type InsertUserSystemRoleParams struct {
	UserID uuid.UUID  `json:"user_id"`
	OrgID  uuid.UUID  `json:"org_id"`
	Role   SystemRole `json:"role"`
}

func (q *Queries) InsertUserSystemRole(ctx context.Context, arg InsertUserSystemRoleParams) error {
	_, err := q.db.ExecContext(ctx, insertUserSystemRole, arg.UserID, arg.OrgID, arg.Role)
	return err
}

const isUserInOrg = `-- name: IsUserInOrg :one
SELECT EXISTS (
    SELECT 1 FROM org_memberships
    WHERE user_id = $1 AND org_id = $2 AND status = 'ACTIVE'
)
`

type IsUserInOrgParams struct {
	UserID uuid.UUID `json:"user_id"`
	OrgID  uuid.UUID `json:"org_id"`
}

// Multi-org membership check: replaces the old single-users.org_id lookup this
// was originally added as (this session's cross-org authorization fixes) — a
// person can now belong to several orgs, so "the user's org" isn't a single
// value anymore, only "is this user an active member of THIS org" is.
func (q *Queries) IsUserInOrg(ctx context.Context, arg IsUserInOrgParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, isUserInOrg, arg.UserID, arg.OrgID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateMembershipStatus = `-- name: UpdateMembershipStatus :exec
UPDATE org_memberships SET status = $1 WHERE user_id = $2 AND org_id = $3
`

type UpdateMembershipStatusParams struct {
	Status UserStatus `json:"status"`
	UserID uuid.UUID  `json:"user_id"`
	OrgID  uuid.UUID  `json:"org_id"`
}

func (q *Queries) UpdateMembershipStatus(ctx context.Context, arg UpdateMembershipStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateMembershipStatus, arg.Status, arg.UserID, arg.OrgID)
	return err
}

const updateUserCredentials = `-- name: UpdateUserCredentials :exec
UPDATE user_credentials
SET password_hash = $2, updated_at = NOW()
WHERE user_id = $1
`

type UpdateUserCredentialsParams struct {
	UserID       uuid.UUID `json:"user_id"`
	PasswordHash string    `json:"password_hash"`
}

func (q *Queries) UpdateUserCredentials(ctx context.Context, arg UpdateUserCredentialsParams) error {
	_, err := q.db.ExecContext(ctx, updateUserCredentials, arg.UserID, arg.PasswordHash)
	return err
}

const updateUserFace = `-- name: UpdateUserFace :exec
UPDATE users SET face_s3_uri = $2 WHERE id = $1
`

type UpdateUserFaceParams struct {
	ID        uuid.UUID      `json:"id"`
	FaceS3Uri sql.NullString `json:"face_s3_uri"`
}

func (q *Queries) UpdateUserFace(ctx context.Context, arg UpdateUserFaceParams) error {
	_, err := q.db.ExecContext(ctx, updateUserFace, arg.ID, arg.FaceS3Uri)
	return err
}

const updateUserOnboarding = `-- name: UpdateUserOnboarding :one
UPDATE users
SET
    first_name = $1,
    last_name = $2,
    phone_number = $3,
    face_s3_uri = $4
WHERE
    email_id = $5
RETURNING id, org_id, status, first_name, last_name, email_id, face_s3_uri, phone_number, created_at
`

type UpdateUserOnboardingParams struct {
	FirstName   sql.NullString `json:"first_name"`
	LastName    sql.NullString `json:"last_name"`
	PhoneNumber sql.NullString `json:"phone_number"`
	FaceS3Uri   sql.NullString `json:"face_s3_uri"`
	EmailID     string         `json:"email_id"`
}

// Shared profile fields only. Flipping the invited org's membership to ACTIVE
// happens as a separate org-scoped call (a person may have other org
// memberships that must be left untouched).
func (q *Queries) UpdateUserOnboarding(ctx context.Context, arg UpdateUserOnboardingParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserOnboarding,
		arg.FirstName,
		arg.LastName,
		arg.PhoneNumber,
		arg.FaceS3Uri,
		arg.EmailID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Status,
		&i.FirstName,
		&i.LastName,
		&i.EmailID,
		&i.FaceS3Uri,
		&i.PhoneNumber,
		&i.CreatedAt,
	)
	return i, err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users 
SET first_name = $2, last_name = $3, phone_number = $4, face_s3_uri = $5
WHERE id = $1
RETURNING id, first_name, last_name, phone_number, face_s3_uri
`

type UpdateUserProfileParams struct {
	ID          uuid.UUID      `json:"id"`
	FirstName   sql.NullString `json:"first_name"`
	LastName    sql.NullString `json:"last_name"`
	PhoneNumber sql.NullString `json:"phone_number"`
	FaceS3Uri   sql.NullString `json:"face_s3_uri"`
}

type UpdateUserProfileRow struct {
	ID          uuid.UUID      `json:"id"`
	FirstName   sql.NullString `json:"first_name"`
	LastName    sql.NullString `json:"last_name"`
	PhoneNumber sql.NullString `json:"phone_number"`
	FaceS3Uri   sql.NullString `json:"face_s3_uri"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (UpdateUserProfileRow, error) {
	row := q.db.QueryRowContext(ctx, updateUserProfile,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.PhoneNumber,
		arg.FaceS3Uri,
	)
	var i UpdateUserProfileRow
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.PhoneNumber,
		&i.FaceS3Uri,
	)
	return i, err
}
