// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT into users (
    org_id, status, first_name, last_name, email_id, phone_number, role
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, org_id, status, first_name, last_name, email_id, phone_number, role, created_at
`

type CreateUserParams struct {
	OrgID       uuid.UUID      `json:"org_id"`
	Status      NullUserStatus `json:"status"`
	FirstName   string         `json:"first_name"`
	LastName    sql.NullString `json:"last_name"`
	EmailID     string         `json:"email_id"`
	PhoneNumber string         `json:"phone_number"`
	Role        NullUserRole   `json:"role"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.OrgID,
		arg.Status,
		arg.FirstName,
		arg.LastName,
		arg.EmailID,
		arg.PhoneNumber,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Status,
		&i.FirstName,
		&i.LastName,
		&i.EmailID,
		&i.PhoneNumber,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const createUserCredentials = `-- name: CreateUserCredentials :one
INSERT into user_credentials (
    user_id, password_hash
) VALUES (
    $1, $2
)
RETURNING user_id, password_hash, updated_at
`

type CreateUserCredentialsParams struct {
	UserID       uuid.UUID `json:"user_id"`
	PasswordHash string    `json:"password_hash"`
}

func (q *Queries) CreateUserCredentials(ctx context.Context, arg CreateUserCredentialsParams) (UserCredential, error) {
	row := q.db.QueryRowContext(ctx, createUserCredentials, arg.UserID, arg.PasswordHash)
	var i UserCredential
	err := row.Scan(&i.UserID, &i.PasswordHash, &i.UpdatedAt)
	return i, err
}
